### ISSUE TITLE
Extreme lag with Sound-Physics-Fabric

### ISSUE THREAD

**Issue by SleepyTonia** [Ladysnake/Effective#10]
https://github.com/vlad2305m/Sound-Physics-Fabric/issues/39
I don't know exactly where the problem lies, but basically as soon as I come close to a waterfall with both mods enabled the game becomes unplayably slow, though it does not crash. Disabling Sound-Physics-Fabric from within its mod menu solves the issue and from the log it's clear that it simply has to deal with too many emitted sounds at once.
[latest.log](https://github.com/Ladysnake/Effective/files/7722994/latest.log)

**Comment by jak3z** [comment]
maybe the problem is that it is constantly playing several and several sounds and overloading the processor calculating all the radii, if that's it, the way to solve it would be to optimize making it generate only 1 sound and it's long I think? I'm saying this without relying on the code
