### ISSUE TITLE
waterfalls noise almost everywhere

### ISSUE THREAD

**Issue by jazqe** [Ladysnake/Effective#100]
**waterfalls are being heard from very far distance + its being heard from caves.**
I have a water filled cave in my survival world just under my base and village and I can hear the waterfall sound from very far away above the surface while its deep down in the caves.
this started bothering me but I just turned off all the water particles and its stopped however no sound well ever be heard for water from the mod. 
I suggest adding few confg sittings to change the distance and loudness of the waterfalls aside of the particles and having the hearing distance adjustable so after an amount of blocks in all direction u should not hear it. but this doesn't really matter if u can chose the distance u want to hear it from, and confg how loud its.

**Comment by lonefelidae16** [comment]
Feels similar to #95 .

It’s a nice issue. I feel the same thing.
Let me ask you few questions from a technical perspective to clarify your suggestion.

* How far is the generally acceptable distance to hear sound of waterfalls?
This is used as the default value for users who don’t have ModMenu like me.

* How far is the maximum distance that can be set in ModMenu?
If not set, you must enter the desired distance manually.

* Are these options really necessary?
Wouldn’t that add to technical debt?

I can implement your suggestion. However, I also feel this issue needs to be discussed carefully.

**Comment by jazqe** [comment]
so yea I was testing a little and I found out that the sounds can be heard almost from 157 to 158 blocks with my currents normal headphones on both the X and the Y axes. (all game sound and windows sound are sat to 100%)

* How far is the generally acceptable distance to hear sound of waterfalls?
1- Maybe between 25 to 30 blocks look like a pretty good distance for it, however if u want to go wild with it maybe up to 50 blocks.
* How far is the maximum distance that can be set in ModMenu?
2- between none(0) and 150 block for people who want to go wiled with it I think.
* Are these options really necessary?
Wouldn’t that add to technical debt?
3-Not really if the hearing distance was reasonable, if the mod in general was a small one or you don't want it to be overcomplicated then its just fine I just see it as a chance to be able to please everyone with one single slide bar for example. 
one thing for sure the hearing distance should be lowered to a decent amount.
and you can see how everyone might have another opinion about the issue, and being able to change it as you desire come in handy. 

I really like the mod by the way keep the good work :).

![1](https://user-images.githubusercontent.com/108681059/177828897-38d3fa40-707c-49c2-a1c7-9dfa10f7f1ed.png)
![2](https://user-images.githubusercontent.com/108681059/177828902-837b28c8-7c9d-4516-9c9c-3e4508081495.png)
![3](https://user-images.githubusercontent.com/108681059/177828903-19f9f3cf-f685-4774-baec-6ba9606a5bf5.png)

**Comment by lonefelidae16** [comment]
Thank you for your reply. Okay, I felt your love for this mod.
I’ll do my best, but I’m not sure if the PR will be merged that I’ll create. Even small patches are waiting to be merged for 2 months, it may be hopeless to request a new feature.

The built jar is available from my repository. [lonefelidae16:Effective/fix/water-falls-sound](https://github.com/lonefelidae16/Effective/commit/dd4b86d18866228d6988b38a58d1933b3e046dc8)
The default value of "Distance To Hear Of Waterfalls" is 36 blocks. Whether this is a reasonable value will be discussed again in PR, I think.

Also, I’m not good at English so please let me know if there are any funny parts in <code>[assets/effective/lang/en_us.json](https://github.com/lonefelidae16/Effective/blob/dd4b86d188/src/main/resources/assets/effective/lang/en_us.json)</code>.

**Comment by jazqe** [comment]
Thanks a lot that you actually did the change, that's really awesome by you, hope it makes it to the new version of the mod.
Yea, I'm not even an English speaker, so who can I judge XD.

Thanks again, all the love.

**Comment by Brittank88** [comment]
> Even small patches are waiting to be merged for 2 months, it may be hopeless to request a new feature.

Worst case, we could author a new mod that uses mixins to target this one and patch it? That should be license-compliant, and allow fixes to be implemented separately.
