### ISSUE TITLE
[Compatibility] Trajectory preview issues

### ISSUE THREAD

**Issue by inflorescence91838** [Ladysnake/Effective#101]
When Effective is installed alongside [Trajectory Preview](https://www.curseforge.com/minecraft/mc-mods/trajectory-preview-fabric/files/all), the water splash effect makes an unbearable and laggy amount of noise. If it is not possible to prevent this, perhaps a configuration to disable only splash noise would suffice.

https://user-images.githubusercontent.com/105180467/177476115-967d597d-6aa1-4506-a6b5-c7541b671283.mp4

**Comment by lonefelidae16** [comment]
I’m not sure if we will come across another mod in the future that spawns what should be displayed in the HUD as Entity, but I was able to apply the patch you requested. The built jar can be found on my repository.
Maybe this patch won’t be merged.

[lonefelidae16:compat/trajectory](https://github.com/lonefelidae16/Effective/commit/db8a244d1fe0d66183abe6483fd2d381aa688b60)

**Comment by inflorescence91838** [comment]
I see, I suspected this was caused by the GUI element also being an entity, but I wasn't sure. I'm attempting to contact the developer of the mod to see if this can be changed.
