### ISSUE TITLE
Stacking raid farm crash (Ticking particle)

### ISSUE THREAD

**Issue by Aqualy** [Ladysnake/Effective#105]
https://bytebin.lucko.me/XcTecyt6Rj
https://crashy.net/MwD5MSElt69pXffGVSNK

Experienced a crash when using[ ianxofoiur's](https://www.youtube.com/watch?v=n3mOlrMGjUg) stacking raid farm. I included the crash logs above.

**Comment by lonefelidae16** [comment]
#87
