### ISSUE TITLE
Sound of waterfalls is EXTREMELY LOUD and does not decrease with distance

### ISSUE THREAD

**Issue by Toilet-Man** [Ladysnake/Effective#11]
The title says it all.
I'm pretty sure one of my mods is doing this, I'll be back with the mod name soon

**Comment by jak3z** [comment]
#3

**Comment by spiralhalo** [comment]
I just tried it and it does properly decrease with distance (1.18, only Effective and Fabric API were present)

**Comment by Athos117** [comment]
The sound indeed decreases with distance, but the waterfalls are still extremely loud. Tried it in three different configurations:

1) 1.18.1. Effective and Fabric API only.
2) 1.18.1. Effective, Fabric API, and Optifabric/Optifine present.
3) 1.18.1. Effective, Fabric API, Optifabric/Optifine and other three player-side mods present (Appleskin, Chatheads, Clear Skies), which are the mods I usually use.

There was no change in the loudness of the waterfalls in the three instances.
