### ISSUE TITLE
Is required on client when installed on server.

### ISSUE THREAD

**Issue by BobzBlue** [Ladysnake/Effective#114]
While it would be simple to remove the mod form the server, it interferes heavily when using port forwarded LAN. The host is forced not to use this mod if even one other player doesn't want to.

**Comment by doctor4t** [comment]
This is a client sided mod, I'm not sure I understand????

**Comment by SurealSulwyn** [comment]
I believe the original poster means that in the case of multiplayer servers, if the server has "Effective" then all connecting players must also have "Effective". In their example, if a single player on a multiplayer server does not want to use "Effective" then the server host cannot use "Effective" either.

**Comment by lonefelidae16** [comment]
I’m not quite sure what the author says “when using port forwarded LAN”, but it seems to occur when “Open to LAN”, perhaps a single player world. I apologize if this assumption is incorrect.

If the host has Effective, clients also must to have Effective. I got a crash.
[latest.log](https://github.com/Ladysnake/Effective/files/9571415/latest.log)

It occurs only on a fabric client. If you use a vanilla client, there is no crashes.

I've been using a dedicated server for multiplayer for so long that I never noticed.

**Comment by UnJust1ce** [comment]
If I host a lan world while using this mod, my friends get a registry remapping error for effective:ambience.waterfall
