### ISSUE TITLE
splashes dont work correctly in 1 block deep water

### ISSUE THREAD

**Issue by DmanMC** [Ladysnake/Effective#119]
this is what it looks like in 1 block of water:
![1blocksploosh](https://user-images.githubusercontent.com/86991346/190877063-40961f27-3341-4dba-88b2-52694ce1e087.gif)

this is what it looks like it 2+ blocks of water
![2blocksploosh](https://user-images.githubusercontent.com/86991346/190877065-5bff20d1-098f-43bf-92b0-a8d38a13912a.gif)

if this is intentional, can there be a config option to allow for 1 block deep splashes?

**Comment by lonefelidae16** [comment]
Are you usinig Effective 1.3? If not, please try to use Effective 1.3.
