### ISSUE TITLE
Particle memory leak.

### ISSUE THREAD

**Issue by jacklollz2** [Ladysnake/Effective#123]
1.19.2, Purpur server.
Waterfall smoke particles continue summoning over and over again without despawning, and fall through the world into the void.
Seems to happen far away, around the edge of the view distance.
Running Sodium+Indium+32x32 resource pack.

JVM Arguments: `-XX:+UnlockExperimentalVMOptions -XX:-UseAdaptiveSizePolicy -XX:+DisableExplicitGC -XX:+UseNUMA -XX:-UseGCOverheadLimit -XX:TargetSurvivorRatio=90 -Dfml.ignorePatchDiscrepancies=true -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:-UsePerfData -XX:MaxGCPauseMillis=200 -XX:ConcGCThreads=2 -XX:+UseG1GC  -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:InitiatingHeapOccupancyPercent=20`

**Comment by ZilverLazarus** [comment]
I'm experiencing the exact same thing. Performance is taking a massive hit and dropping me from 120 fps to 12 fps when particles don't despawn.

**Comment by jacklollz2** [comment]
Still happening with latest version.

**Comment by jacklollz2** [comment]
Alright well since this isn't getting addressed I can't recommend this to anyone, and I will actively advise people not to use this.

**Comment by Arathain** [comment]
I will do my best to investigate, sorry for the delay.

**Comment by Arathain** [comment]
@jacklollz2 I've been unable to replicate the issue after ~2 hours of debugging on version 1.6, are you able to provide a world/specific case I can use to somewhat reliably replicate the problem?

**Comment by jacklollz2** [comment]
It appears to be related to the config file, changing settings on the config can trigger this.

**Comment by Arathain** [comment]
Are you able to find a specific config that'd cause the crash, and send it? It's fine if no, but I need somewhere to start w/ debugging this
