### ISSUE TITLE
Random crash when saving and exiting back to main menu

### ISSUE THREAD

**Issue by MechanosG** [Ladysnake/Effective#124]
https://mclo.gs/6FVbl1B

It seems to not always happen, and I haven't figured out if I'm doing anything to make it happen more or less frequently.  When it does happen, the load screen that says it's saving the world, starts chugging like mad.  Console will show this crash happening repeatedly, I assume because of not enough crashes trying to recover.  But it eventually gives up and boots me out of the game.

**Comment by Brittank88** [comment]
I second this: https://mclo.gs/IM2V5LN

**Comment by piebaker** [comment]
Looks like #146 #147 #149 are all duplicates of this issue. I have the same issue. Clean crash (ie click exit to menu, then it dumps straight to desktop) on single-player game exit. 

https://mclo.gs/q8fF5wr

Log included

**Comment by Arathain** [comment]
*Presumably* fixed in indev 1.19.3 version, will close when released.
