### ISSUE TITLE
[Suggestion] Tweaked sounds for when player is underwater

### ISSUE THREAD

**Issue by LolJohn11** [Ladysnake/Effective#125]
Currently, the sounds of waterfalls\cascades are the same both above and underwater.  Since Minecraft adds some changes to the sounds when the player is underwater (which improves immersion), my suggestion is to make this mod's sounds change when the player is underwater.
Here are video examples of how I would imagine that would work (I've adjusted the sound in an external audio editor software):
[Before](https://imgur.com/MD9djed)
[After](https://imgur.com/PYcYipj)
I don't know how vanilla Minecraft changes the sounds underwater - applies an audio filter to the sounds, or plays back separate "underwater" sounds - but could something like this be done for this mod?

**Comment by doctor4t** [comment]
Minecraft doesn't change sounds underwater, the only instance I can think of that does that is guardians with separated sounds. The rest is played just the same.

If you want more immersion like this I recommend Sound Physics Remastered, I took special care to make sure Effective is compatible with it.

**Comment by LolJohn11** [comment]
I did try it with the Sound Physics mod and it works great! Thanks for the suggestion.
