### ISSUE TITLE
New version of effective crashes upon use

### ISSUE THREAD

**Issue by NoobiusMcGuffin** [Ladysnake/Effective#127]
Effective crashes upon using the newest version 1.4

**Comment by FuzzyLeo** [comment]
Same issue here

heres my crash report
[crash-2022-10-21_16.04.29-client.txt](https://github.com/Ladysnake/Effective/files/9840904/crash-2022-10-21_16.04.29-client.txt)

**Comment by NoobiusMcGuffin** [comment]
> Same issue here
> 
> heres my crash report [crash-2022-10-21_16.04.29-client.txt](https://github.com/Ladysnake/Effective/files/9840904/crash-2022-10-21_16.04.29-client.txt)

Figured out what was wrong, backport fabric api to [[1.19.2] Fabric API 0.63.0+1.19.2] and it should be good

**Comment by FuzzyLeo** [comment]
im on that version already though

**Comment by PaladinFallen** [comment]
[latest.log](https://github.com/Ladysnake/Effective/files/9843385/latest.log)

Crashed as well, went back to 1.3 until fix..

**Comment by gsf-twod** [comment]
Apparently 1.4 depends on Satin API, so try downloading that.

**Comment by gsf-twod** [comment]
> Same issue here
> 
> heres my crash report [crash-2022-10-21_16.04.29-client.txt](https://github.com/Ladysnake/Effective/files/9840904/crash-2022-10-21_16.04.29-client.txt)

Regarding your crash report, downloading [Satin API](https://www.curseforge.com/minecraft/mc-mods/satin-api) solved the issue for me and a couple of people. I'm not sure, but it seems that it's a dependency now?

**Comment by Disguys** [comment]
After installing [**Satin API**](https://www.curseforge.com/minecraft/mc-mods/satin-api), mod run on version 1.4 without any problems.

**Comment by FuzzyLeo** [comment]
that fixed it for me too, weird that its a dependancy now without it actually saying anywhere

**Comment by MarkinhosMLP** [comment]
after installing satin api STILLS not working for me

**Comment by EeveeEuphoria** [comment]
I can also confirm that using the Satin API fixes things for me.

**Comment by salarua** [comment]
I can confirm I have that same problem ([log here](https://mclo.gs/y0qfvot)) and that Satin API fixes it ([log here](https://mclo.gs/9eQBz2v)).

**Comment by McModknower** [comment]
Another Person on the MultiMC Discord had the same problem with having to add Satin. This should be added in the file where the modloader looks for dependencies.

**Comment by Mahadbaloch** [comment]
Satin itself crashes the game tho bhahahah

**Comment by thealzhe** [comment]
Same issue, same fix.

**Comment by doctor4t** [comment]
Fixed in latest. If you have an incompatibility with Satin, I cannot help without you sharing the crash report :)
I invite you to do so on the Satin repo: https://github.com/Ladysnake/Satin/
