### ISSUE TITLE
[BUG] Console spammed with "false"

### ISSUE THREAD

**Issue by Shazuli** [Ladysnake/Effective#129]
With Effective and required library mods installed the log is spammed with "false".

```
...
false
false
false
false
false
false
false
false
false
false
false
[16:28:31] [Server thread/INFO]: Saving and pausing game...
[16:28:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
false
false
[16:28:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[16:28:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
false
false
false
false
false
false
false
false
false
false
false
false
...
```

**Comment by EduardoJauch** [comment]
I confirm this on version 1.4. It does not happen on version 1.3

**Comment by Eman-3600** [comment]
looks like someone left a debug statement in the release

**Comment by EduardoJauch** [comment]
> looks like someone left a debug statement in the release

Thought the same thing. I am looking into the code but didn't find it yet.

**Comment by EduardoJauch** [comment]
Maybe this is the culprit:

```
private static RenderLayer replaceRenderLayer(RenderLayer base) {
        System.out.println(isRgb);
        if (isRgb) {
            System.out.println("TEST");
            return Effective.RAINBOW_SHADER.getRenderLayer(base);
        }

        return base;
    }
```
As isRgb seems to be false, it is constantly printing false to the console output

**Comment by Eman-3600** [comment]
probably

**Comment by EduardoJauch** [comment]
Just to be clear, the code is not there anymore, but the release may have been made before the code was removed.
Most likely 1.5 will fix this problem.

**Comment by doctor4t** [comment]
haha I'm a fucking idiot yes

**Comment by doctor4t** [comment]
will be fixed next release sorry about that

**Comment by DonFlymoor** [comment]
Still a problem, and took me a very long time to figure out that this was the mod creating the false log. I would recommend updating the curseforge mod to fix the problem asap
