### ISSUE TITLE
1.16.5 - 1.17.1 support please

### ISSUE THREAD

**Issue by Dingroupcr** [Ladysnake/Effective#13]
My client side modpack is 1.16.5 and its my personal favorite modpack
So I wanna add this mod to it but I cant
And another issue is most of the mod in Curseforge support 1.16.5

Sorry for bad language
Im new to github

**Comment by ILIKEHAAM** [comment]
I completely agree, I'm in 1.17.1 because I refuse to update to a version that sucks, so support for good versions of minecraft would be great.

**Comment by sudofox** [comment]
I'm still using 1.17.1 myself (with ViaFabric to play on 1.18.1 server) so likewise.

Interestingly it does load in 1.17.1, shows in ModMenu, etc but doesn't seem to do anything
