### ISSUE TITLE
1.4 Version adds new features and new incompatibilities as well

### ISSUE THREAD

**Issue by MarkinhosMLP** [Ladysnake/Effective#130]
doesnt works with optifine or optifabric anymore, had to go back to effective 1.3 sadly... i was so excited about planktons and the hypnotizing glow squid but now i cant play it anymore...
sodium doesnt works well in my computer and also theres a lot of features from optifine which even mods cant replace them, and i know that most of the optifine incompatibilities is because of optifine being closed source, but at the same time, if it was fully compatible before, why it isnt anymore?? this is kinda sad and disappointing... i believe that a lot of people would like to play with optifine and effective, for example using the fresh animations resource pack which cant be used without optifine
this is sad, we want optifine compatibility back :((

**Comment by ttrafford7** [comment]
this

**Comment by Arathain** [comment]
with the newest additions, it is practically impossible to support OptiFine. I'd heavily suggest considering other options if you want to keep using Effective.

**Comment by tsvyakh** [comment]
> with the newest additions, it is practically impossible to support OptiFine. I'd heavily suggest considering other options if you want to keep using Effective.

hope it is possible to make these features using Canvas Renderer mod coz' it sucks if not

**Comment by tsvyakh** [comment]
> > with the newest additions, it is practically impossible to support OptiFine. I'd heavily suggest considering other options if you want to keep using Effective.
> 
> hope it is possible to make these features using Canvas Renderer mod coz' it sucks if not

oh wait. i was thinking it was because of Satin API OptiFine incompatibility but uhh guess not

**Comment by MarkinhosMLP** [comment]
> with the newest additions, it is practically impossible to support OptiFine. I'd heavily suggest considering other options if you want to keep using Effective.

bro, this is really bad, old computers, computers with integrated or no graphic cards run slowly in sodium than in optifine, which is my case, also i have to download about more than 20 mods to have 70% or less of the features i do use with optifine
with that said, it means that i would have to worry about incompatibilities with another TWENTY MODS..

Except for optimization features, here is a list of mods you i would need for 70% or even less for the optifine features

• Iris - Shaders
• Cit Resewn - Cit
• Entity Textures Features - Random entities + Emissives
• Animatica - animations
• Optigui - gui texture features
• Optifine capes or other capes mods - Capes
• Zoomify or other zoom mod - Zoom
• Colormatic - Colormaps
• Lambda Dynamic Lights 
• Lambda Better Grass
• Cull Leaves - Fast Leaves
• Continuity or ConnectedBlockTextures - CTM 
• CEM MOD - Cem (which has like 30% only of cem features) 
• Fabric Skyboxes 
• Dark Loading Screen or Puzzle - Custom loading screen colors

**Comment by MarkinhosMLP** [comment]
not every old computer runs slowly in sodium, there are some exceptions, but a lot of it does work bad with sodium which definetly is a weird behavior but yeah it happens and i hate this a lot

effective was so far one of by favorite mods but now i have to choose between playing without it or without a lot of other features i play with and with low quality performance in my game


except for the fact that effective probably will be dropping fabric support and go to quilt (which has a lot of mods incompatibilities and also is 100% incompatible with optifine) 


it sucks a lot

**Comment by tsvyakh** [comment]
> not every old computer runs slowly in sodium, there are some exceptions, but a lot of it does work bad with sodium which definetly is a weird behavior but yeah it happens and i hate this a lot
> 
> effective was so far one of by favorite mods but now i have to choose between playing without it or without a lot of other features i play with and with low quality performance in my game
> 
> except for the fact that effective probably will be dropping fabric support and go to quilt (which has a lot of mods incompatibilities and also is 100% incompatible with optifine)
> 
> it sucks a lot

effective moves to quilt!? sucks so much, man

**Comment by tsvyakh** [comment]
personally, i use optifine only because of the Fresh Animations resource pack. i really hope that one day we'll get full CEM on Fabric

**Comment by Arathain** [comment]
Quilt is incompatible with OptiFabric for good reason - the mod has essentially been dropped. In terms of other mod incompatibilities, they can all be accessed [here](https://forum.quiltmc.org/t/mod-incompatibility-megathread/261). Effective is switching to Quilt mostly because of technical reasons, however neither I nor rat are comfortable with Fabric's community & leadership. I understand this might be saddening, however it is a calculated short-term loss for a long-term gain.

**Comment by MarkinhosMLP** [comment]
> personally, i use optifine only because of the Fresh Animations resource pack. i really hope that one day we'll get full CEM on Fabric

bro, i use a lot of resource packs but i love fresh animations its probably the best resource pack ever made to the entire minecraft community and a lot of people use fresh animations together with the effective mod

**Comment by MarkinhosMLP** [comment]
> effective moves to quilt!? sucks so much, man

sadly it will be moving idk if in the next release or whatever, but it will

**Comment by MarkinhosMLP** [comment]
> Quilt is incompatible with OptiFabric for good reason - the mod has essentially been dropped. In terms of other mod incompatibilities, they can all be accessed [here](https://forum.quiltmc.org/t/mod-incompatibility-megathread/261). Effective is switching to Quilt mostly because of technical reasons, however neither I nor rat are comfortable with Fabric's community & leadership. I understand this might be saddening, however it is a calculated short-term loss for a long-term gain.

terms of technical reasons is "ok" but stills really really bad since it will affect a lot of users/players who like the mod so people will have to "change" or "drop" and this is actually pretty sad
 
and about the... fabric community and leadership?? idk exactly what it is about but it has nothing to do with the casual players who like mods and stuff like that, its sad that this is one of the reasons were being affected about the mod moving

**Comment by tsvyakh** [comment]
> > Quilt is incompatible with OptiFabric for good reason - the mod has essentially been dropped. In terms of other mod incompatibilities, they can all be accessed [here](https://forum.quiltmc.org/t/mod-incompatibility-megathread/261). Effective is switching to Quilt mostly because of technical reasons, however neither I nor rat are comfortable with Fabric's community & leadership. I understand this might be saddening, however it is a calculated short-term loss for a long-term gain.
> 
> terms of technical reasons is "ok" but stills really really bad since it will affect a lot of users/players who like the mod so people will have to "change" or "drop" and this is actually pretty sad
> 
> and about the... fabric community and leadership?? idk exactly what it is about but it has nothing to do with the casual players who like mods and stuff like that, its sad that this is one of the reasons of why we are being affected about the mod moving

the second one is so freaking true

**Comment by Arathain** [comment]
Well, either way there's nothing to be done here, seeing as OptiFine compatibility will not be maintained because of just how much of a pain it'd be, so I'm closing this issue.

**Comment by MarkinhosMLP** [comment]
this is sad damn
