### ISSUE TITLE
It's not loading on 1.4.1

### ISSUE THREAD

**Issue by FanofGamess** [Ladysnake/Effective#135]
I tried using effective 1.4.1 and didn't work and I then tried to go back to 1.4 and it crashed and I had Fabric API but it still didn't work.

**Comment by FanofGamess** [comment]
Here's my log.
[latest.log](https://github.com/Ladysnake/Effective/files/9896297/latest.log)

**Comment by Timolino456** [comment]
The new version of the mod now requires Quilt instead of Fabric.

**Comment by FanofGamess** [comment]
> The new version of the mod now requires Quilt instead of Fabric.

Thanks.

**Comment by Arathain** [comment]
👍
