### ISSUE TITLE
A modloader switch is not a patch...

### ISSUE THREAD

**Issue by Chris6ix** [Ladysnake/Effective#136]
Adding an effect to the glow squid is a minor update, but switching the modloader is a patch?
Not confusing at all...

Also, doesn't help that "Migrated the mod to Quilt" is listed as the last thing in the changelog, like it's some tiny, unimportant detail...

Awful.

**Comment by SekoiaTree** [comment]
There's a massive banner at the top of the curseforge page.

I'd personally agree that it's not a patch, but now that it's out... not much that can be done afaik.

**Comment by Chris6ix** [comment]
> There's a massive banner at the top of the curseforge page.

Yeah, I saw that one later when I tried to find out why the mod wasn't working.
I have direct links to the "Files" tab of all my mods saved, that I use to sometimes check for newer versions, meaning that I didn't even see that banner at first.
I also didn't know what "Quilt" even is before.
