### ISSUE TITLE
It just dosn't work on my modlist and I can't figure out why even tho it's installed

### ISSUE THREAD

**Issue by BjornIceBorn** [Ladysnake/Effective#137]
I will send my mod list hoping someone can help me out 
[Light Craft 1.19.2 (842% more FPS than OptiFine)  The best FPS Boost Pack [ NEW 1.19.2 VERSION ]- 1.19.2 - 4.5.1.zip](https://github.com/Ladysnake/Effective/files/9933650/Light.Craft.1.19.2.842.more.FPS.than.OptiFine.The.best.FPS.Boost.Pack.NEW.1.19.2.VERSION.-.1.19.2.-.4.5.1.zip)

**Comment by Nyrif** [comment]
happens to me too, except on fabric

**Comment by s1lv3r-p0tat0** [comment]
for fabric try to see if you have the good version and not the quilt version like me, plus the satin api.

**Comment by Nyrif** [comment]
I removed optifabric and optifine and switched to sodium and 1.4 of effective started working, so if you have optifabric/optifine, uninstall them
