### ISSUE TITLE
Crashing rain (Quilt 1.19.2)

### ISSUE THREAD

**Issue by Nekkok** [Ladysnake/Effective#138]
Hi! I just wanted to share this crash as every time it rains, the game crashes. Thank you n_n
[crash-2022-11-04_23.39.30-client.txt](https://github.com/Ladysnake/Effective/files/9943353/crash-2022-11-04_23.39.30-client.txt)

**Comment by doctor4t** [comment]
I can't seem to be able to reproduce, anything specific I should try?
