### ISSUE TITLE
Effective not showing up in Modmenu and not working

### ISSUE THREAD

**Issue by wenoukiz** [Ladysnake/Effective#145]
I've installed the most recent version of effective today and the game launches without any problems but the mod doesnt show up in the Modmenu list and when I test in-game it doesnt seem to be running. Although it's in my mod folder and I run the most recent fabric 1.19.2 loader. Is it a known issue ? Does it have anything to do with Quilt in someway ?

**Comment by AzCreep** [comment]
oh my por thing no one responded to you don't worry fam i got you look use the version 1.4 (DON'T USE 1.4.1) and use the Satin API aswell it's a dependencie for v1.4 if you don't want it the only solution you got it's the V1.3 but yeah that's the high you can go on versions after that it won't load on fabric

**Comment by wenoukiz** [comment]
Ohh ok thanks a lot, I used the Quilt version on Fabric that is why it didn’t work. Although is there some known incompatibility with Satin API ? Because I’m using many mods.

**Comment by AzCreep** [comment]
Oh i see well try using the v1.3 then see if works if it does well sadly it will be the only working version i believe

**Comment by Xiribidus** [comment]
> Although is there some known incompatibility with Satin API ? Because I’m using many mods.

Satin API is actually a dependency for Effective
