### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by chen-Futuro** [Ladysnake/Effective#151]
Effective1.21 for 1.18.2 Fabric doesn't seem to work correctly, all splashes look black, is this a bug?
Will 1.18.2 get an updated Effective version to 1.6 or above?

**Comment by Arathain** [comment]
the newest Effective version relies on an API that is not available for 1.18.2. We unfortunately do not have LTS for any minecraft version, so I fear you'd have to update to at least 1.3 in order for the black splash bug to be fixed for you. I apologise for the inconvenience ^^'.
