### ISSUE TITLE
game crash,1.19.2 Fabric

### ISSUE THREAD

**Issue by DarkCrystalll** [Ladysnake/Effective#153]
[minecraft-exported-crash-info-2022-11-28T15-54-43.zip](https://github.com/Ladysnake/Effective/files/10101683/minecraft-exported-crash-info-2022-11-28T15-54-43.zip)

**Comment by Zensonaton** [comment]
This mod is for Quilt.

**Comment by DarkCrystalll** [comment]
![image](https://user-images.githubusercontent.com/118486124/204731332-9fd4007b-ebb8-48be-8ec1-3eccc175ac0b.png)ummm

**Comment by DarkCrystalll** [comment]
Maybe I installed the wrong version
