### ISSUE TITLE
Add to Modrinth

### ISSUE THREAD

**Issue by SylvKT** [Ladysnake/Effective#154]
Modrinth added monetization support.

**Comment by realqdbp** [comment]
Yes please, way better site. I hat curseforge as it takes ages to load :)

**Comment by GitsurferQwerty** [comment]
I'm currently switching from CurseForge to Modrinth because Modrinth seems more popular, better loading time and also seems more "modern" if you know what I mean while CurseForge is really hard to use. I support this.

**Comment by Brancieq-Paul** [comment]
Will you support both ? CurseForge and modrinth ?

**Comment by GitsurferQwerty** [comment]
> 

I don't think there would be any reason for them to remove Effective from CurseForge if they do end up making a Modrinth version. CurseForge is still used a lot by the community, so to remove Effective from it would be outright stupid.

**Comment by PolyframeX** [comment]
Hope this does go through though, as curseforge is laggy for alot of users. This just makes it way more accessible.
