### ISSUE TITLE
Splashes appear not loaded and are the purple and black texture im using curseforge with lasted version of forge and your mod with 1.19.2 mincraft

### ISSUE THREAD

**Issue by Toasti58** [Ladysnake/Effective#157]

**Comment by Toasti58** [comment]
![image](https://user-images.githubusercontent.com/119913057/209395793-ec8b408b-44d1-4f4b-a1ad-3723103474ab.png)

**Comment by Toasti58** [comment]
only happens sometimes

**Comment by Eman-3600** [comment]
can you send a log?

**Comment by Arathain** [comment]
the forge version is not supported by us; please visit https://github.com/bottomtextdanny/Effective-Forge-/issues for issues with the Forge version.
