### ISSUE TITLE
Newer versions of Effective remove a sound from the game

### ISSUE THREAD

**Issue by spaghettube** [Ladysnake/Effective#159]
Hey there. Ever since 1.3, small water hops create a big splash texture and play the "entity.generic.splash" sound. I'm assuming this happens because ever since that version every bob on the water is now considered by the mod, what was before on 1.2.2, a big splash. Here's a couple videos to clear up what I'm trying to explain:
**1.2.2**
https://user-images.githubusercontent.com/101492556/210055265-73878d3f-7b99-4e85-9d8c-c0c572502073.mp4

**1.4**
https://user-images.githubusercontent.com/101492556/210055344-a4c9ccb0-8439-4092-9f0e-f24a80090e51.mp4

As you can see, on any version >1.2.2 a big splash is created no matter if the player hops on the water or jumps in the water. The issue here would be that this change removes the "entity.player.splash" sound from the game, since now every water hop will be considered a big splash, and will play "entity.generic.splash". 

This is an easy and common oversight by many since both sounds are the same and only the volume change, but it wasn't to me because I develop a sound based resource pack and it is very noticeable and can sound very wrong, as you can tell on second video.

I'd like to suggest you to create an effective sound node for these sounds, or to not replace "entity.player.splash" to "entity.generic.splash" on water hops in order to not completely remove "entity.player.splash" from the game. If you have any other ideas on how to go about this please do share with me :)

**Comment by Arathain** [comment]
It should be fixed in the latest commit - are you able to build the mod to check, or would you require a .jar build?

**Comment by spaghettube** [comment]
i can build it

**Comment by spaghettube** [comment]
yep, seems like its all good now, appreciate this very niche fix

**Comment by Arathain** [comment]
Nice! closing this issue then, the fix will be in the 1.19.3 release once rat comes back from his trip & makes his changes
