### ISSUE TITLE
Update to 1.19.3 (Game crashes)

### ISSUE THREAD

**Issue by MerBudd** [Ladysnake/Effective#160]
Hi, I was just trying to use the mod with a bunch of other mods. Once I finally set everything up, the game crashed every time it tried to load. I narrowed the issue down to Effective. I think it's crashing because effective doesn't support 1.19.3? I thought it would be fine but I don't know. It might be because of another issue but it's most likely because it doesn't support 1.19.3?

**Comment by Arathain** [comment]
That is correct - the update is mostly waiting for the Illuminations merger, so in the meantime there's not much else to do other than wait

**Comment by Aces-and-Jacks** [comment]
if you look at the commit history you can see the current progress

**Comment by Xiribidus** [comment]
Closing this issue considering #179 , the mod will update whenever or if it ever gets ready, thank y'all for your patience.
