### ISSUE TITLE
Elaboration on Quilt/Fabric mod compatibility

### ISSUE THREAD

**Issue by GitsurferQwerty** [Ladysnake/Effective#162]
This isn't in the slightest asking about the port to Quilt, but I need some elaboration on how the incompatibility-compatibility thing works.
I'm reading on one "issue" that Effective will not work on any Fabric mod, but I'm struggling to see whether or not that's the case.

This is my mod list for 1.19.3: 
https://paste.gg/p/anonymous/1d6fda057e6e4419920bf46466983d8f

I was wondering if someone could tell me whether or not Effective is not compatible with any of these mods or ANY Fabric mod in that matter, because I was having trouble on a clear answer. If there are incompatible mods thats fine, but I'm wondering if I need to add any APIs or stuff like that.

**Comment by GitsurferQwerty** [comment]
I know Effective is still on 1.19.2, but I'm just wanting to know in general for once 1.19.3 version is released.

**Comment by UpcraftLP** [comment]
It is incompatible with fabric <ins>loader</ins>, that is, the underlying modloader, not some mod.

**Comment by GitsurferQwerty** [comment]
Oh. So Effective is pretty much incompatible with any Fabric mod?

**Comment by Eman-3600** [comment]
It means you need to use the Quilt loader instead of the Fabric loader, and you need to use the Quilt Standard Libraries instead of the Fabric API. You can play Fabric mods using Quilt, but you need Quilt to play Effective.

**Comment by GitsurferQwerty** [comment]
Are any of these mods incompatible with Quilt Loader/Quilt Library?

**Comment by Eman-3600** [comment]
They're probably all fine. I can't say for sure because I'm not omniscient, but the likelihood of there being an issue is low.

**Comment by GitsurferQwerty** [comment]
Alrighty. Hopefully none of them are incompatible because Effective is a really nice mod.
