### ISSUE TITLE
fabric reference

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Ladysnake/Effective#165]
Since the original issue is locked, just wanted to point out in the about section on the GitHub it still references fabric

**Comment by Aces-and-Jacks** [comment]
I meant it still references fabric. incase you see this in mail

**Comment by Xiribidus** [comment]
https://github.com/Ladysnake/Effective/pull/166
thanks

**Comment by Aces-and-Jacks** [comment]
![image](https://user-images.githubusercontent.com/106651342/215830902-6f32defe-89b3-4507-baff-4144ccf05026.jpeg)

**Comment by Pyrofab** [comment]
Done.
