### ISSUE TITLE
[Bug] Log spam on quilt

### ISSUE THREAD

**Issue by jonask028** [Ladysnake/Effective#168]
When i play i get spammed with both opengl 1281 errors (until i disabled gl debug logging in options.txt) and i still get issues with [ladysnake.effective.mixin.jebglowsquid.FeatureRendererMixin] false. It prints them multiple times a millisecond and quickly reaches the 100000 line log limit. [Log](https://mclo.gs/DWRdptn)

**Comment by Arathain** [comment]
What version were you using?

**Comment by jonask028** [comment]
1.4

**Comment by Arathain** [comment]
is it fixed on latest release?
