### ISSUE TITLE
minecraft log overflow

### ISSUE THREAD

**Issue by Alxkory** [Ladysnake/Effective#173]
The log in prism launcher quickly ovcerflows with "False" prints

![image](https://user-images.githubusercontent.com/22823766/225935331-04c7084a-d4bd-4499-8d4f-ce224586b361.png)

**Comment by arazadaz** [comment]
Yeah. This is a super easy fix. Once this gets taken care of, could it be patched to the fabric version? Quilt is great and all, but it's still got a few mods that don't play nice with quilt from fabric.
