### ISSUE TITLE
Update to 1.19.4?

### ISSUE THREAD

**Issue by Kavin7000** [Ladysnake/Effective#174]
I tested Effective for both 1.19.3 and 1.19.4 on Quilt and Fabric. It seems to crash on launch. Tried changing the Minecraft Version Required in the fabric.mod.json/quilt.mod.json but that too doesn't seem to work.

**Comment by SuperNoobYT** [comment]
If you compile the main branches it work on 1.19.3, but some features from illumination are missing and some effect doesn't work correctly.
1.19.4 doesn't work at all :/ I even tried to update the mod myself but the issue seem to be lodestonelib not working in 1.19.4 and i have no idea how to make it work.
So, yep we have to wait until this great mod come out for 1.19.3/1.19.4

**Comment by theoparis** [comment]
I would totally attempt to fork and update it too but the license raises concerns.

**Comment by jayhawker6** [comment]
> I would totally attempt to fork and update it too but the license raises concerns. Unless I read #161 wrong it seems like it isn't allowed 😕

You have every right to fork it based on GitHub's ToS (I am not a lawyer this is not legal advice), but either way, I would recommend that you take a look at this. Since this is a public repo, they grant these rights by agreeing to the GitHub ToS by using the platform. https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users

**Comment by Arathain** [comment]
Forking the project is allowed by the ToS, yes. Making modifications to said fork or uploading it anywhere outside of github is in the grey area though, with the latter one being 100% forbidden. @doctor4t can weigh in on this if needed, but to my knowledge the port is coming Soon:tm:, aka when they have the free time & motivation to update it.

**Comment by SpiritFancy** [comment]
it being out for 1.19.4 is literally just my dream

**Comment by osumansasu** [comment]
Can someone explain why they intentionally didn't support fabric? It seems kind of weird to just not be in favor of creating the mod for one of the largest loaders

**Comment by Xiribidus** [comment]
It's simple: one of effectives dependencies is quilt exclusive

**Comment by Xiribidus** [comment]
Closing this issue considering #179 , the mod will update whenever or if it ever gets ready, thank y'all for your patience.
