### ISSUE TITLE
Make it for older versions

### ISSUE THREAD

**Issue by ElroMaxGG** [Ladysnake/Effective#176]
_(i don't speak english)_ **Yo creo** que también hay que fijarse en **otras versiones**, también pensando por la gente que no le funciona la **1.18.X - 1.19.X**, en mi caso si me funciona pero no soy de usar esas versiones, mas por los sistemas nuevos de seguridad, yo creo que deberían por lo menos intentar hacer el mod **1.16.X (principalmente 1.16.5), 1.15.X 1.14.X**.

**Comment by Xiribidus** [comment]
Sorry, we don't do backports
