### ISSUE TITLE
PR's for new versions?

### ISSUE THREAD

**Issue by SzczurekYT** [Ladysnake/Effective#180]
>Y'all have no idea how much effort Rat spends on his daytime job, please stop being so dismissive when it comes to a mod he updates on the time he has left after that. It is okay to be pained because a mod you like is in a state of stasis, but it is not acceptable to dogpile on the creator in hopes that they will cave at the cost of their mental health.

>I will be closing this issue as it was pretty much destined to be a repository for complaints.

_Originally posted by @Pyrofab in https://github.com/Ladysnake/Effective/issues/179#issuecomment-1582852640_

Hello
I see that some of the Ladysnake mods are stale, with creators not having time to update it. That's understandable.
I would like to ask if you are interested in accepting / reviewing PR's that update these mods to new versions?
Because I think I could maybe update some of them for you.
I already made a [PR](https://github.com/Ladysnake/Impaled/pull/45) for Impaled for 1.19.3 (oh wait it has conflicts now, need to fix that), and I have also Blast for 1.19.3, on my pc.
Now I might update Effective to 1.19.4, as it was a cool mod, and I miss it.
Would you be interested in this?

**Comment by Pyrofab** [comment]
Hm, fair enough, I can at least review it and merge it if you do the PR. The release part will still most likely have to wait for RAT though.

**Comment by SzczurekYT** [comment]
> Hm, fair enough, I can at least review it and merge it if you do the PR. The release part will still most likely have to wait for RAT though.

I made it 😄
https://github.com/Ladysnake/Effective/pull/181

**Comment by doctor4t** [comment]
> > Y'all have no idea how much effort Rat spends on his daytime job, please stop being so dismissive when it comes to a mod he updates on the time he has left after that. It is okay to be pained because a mod you like is in a state of stasis, but it is not acceptable to dogpile on the creator in hopes that they will cave at the cost of their mental health.
> 
> > I will be closing this issue as it was pretty much destined to be a repository for complaints.
> 
> _Originally posted by @Pyrofab in [#179 (comment)](https://github.com/Ladysnake/Effective/issues/179#issuecomment-1582852640)_
> 
> Hello I see that some of the Ladysnake mods are stale, with creators not having time to update it. That's understandable. I would like to ask if you are interested in accepting / reviewing PR's that update these mods to new versions? Because I think I could maybe update some of them for you. I already made a [PR](https://github.com/Ladysnake/Impaled/pull/45) for Impaled for 1.19.3 (oh wait it has conflicts now, need to fix that), and I have also Blast for 1.19.3, on my pc. Now I might update Effective to 1.19.4, as it was a cool mod, and I miss it. Would you be interested in this?

Hi! Yeah sorry, I tend to be so busy I can't check this repo at all, even when it comes to merging PRs. If you wanna PR some updates I wouldn't be against it, but sometimes I'm so busy I can't even check that, but it would be appreciated. I'll do my best!
