### ISSUE TITLE
Ripple effects are incorrectly rendered

### ISSUE THREAD

**Issue by vistis** [Ladysnake/Effective#185]
When it rains, the ripple effects should be ideally rendered on top of the water texture, but it renders it underneath the water instead, making it not visible from the surface like it used to. 
![2023-06-24_09 28 30](https://github.com/Ladysnake/Effective/assets/95111346/5ea35f8e-60cd-4150-85c1-a020d1e22874)
![2023-06-24_09 33 11](https://github.com/Ladysnake/Effective/assets/95111346/9bf143a3-1c91-4bcd-a2a8-18151f6f7eb1)

It's still the case with a fresh install with just Effective and Quilted Fabric API
![2023-06-24_09 37 31](https://github.com/Ladysnake/Effective/assets/95111346/a1a072f3-1e41-4f2d-a1c2-07112465bd2c)
![2023-06-24_09 37 43](https://github.com/Ladysnake/Effective/assets/95111346/4397ae1a-cc75-4a27-813f-2da9016246b9)

This issue is present in version:
- 2.0+1.19.2 (Modrinth release)
- 2.0.1+1.19.2 (built using commit ddc6a66)

**Comment by doctor4t** [comment]
do you use any other mods?

**Comment by vistis** [comment]
Yes. But I've also tested it on an installation with only Quilted Fabric API and Effective, and the issue is still present.

**Comment by doctor4t** [comment]
Fixed in 2.1.1
