### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by SorkoPiko** [Ladysnake/Effective#187]
Hey, I found this mod recently, and would love to use it. However, it only works for 1.19.2, and if using on 1.20.1, it causes Quilt to crash. If you could update this to 1.20.1, it would be great. Thanks!

**Comment by lostopkk** [comment]
i want that too

**Comment by SorkoPiko** [comment]
Why was this closed? It hasn't upgraded yet, so why mark it as being done? If you could re-open this, and close it when we can actually download a 1.20.1 release, that would be great.

**Comment by doctor4t** [comment]
You know what would be truly great? If you read the FAQ.
I keep issues for bug reports and feature suggestions.
