### ISSUE TITLE
can the newer versions of effective be ported to fabric by another person?

### ISSUE THREAD

**Issue by mateus3c** [Ladysnake/Effective#189]
would you allow this?

**Comment by JadedChara** [comment]
If you want to utilize Forge mods alongside this, there is already a compatibility API that would facilitate loading those mods within a Fabric, and thus theoretically Quilt environment, though I have not yet tested it myself. Likewise, Fabric in turn should work for the most part on Quilt. There was a previous port of this mod for Forge, but given the semi-recent things that have transpired regarding one of the lead developers, that one has likely fallen by the wayside for the foreseeable future, as said developer is still very much present on the Discord, and in the community in general.

**Comment by mateus3c** [comment]
> > Q: Can I port this mod to Forge / Fabric?
> > A: No. I am not comfortable with ports of my mod being made for other loaders I do not wish to support.
> 
> This is referencing the questioner as the one who would attempt to port the mod.

oh.. thats so sad... the only problem I have with quilt is that it has a lot of incompatibilities and a good amount of modders dont even pretend to ever support quilt... Its sad how the modding community keeps getting fragmentated. I wonder whats next :(
