### ISSUE TITLE
downgrade to fabric 1.17 pls

### ISSUE THREAD

**Issue by SiMonZWolf** [Ladysnake/Effective#19]

**Comment by Degostor** [comment]
yes please

**Comment by xanthian** [comment]
it works already. just try it instead of begging.

**Comment by Degostor** [comment]
huh?

**Comment by Degostor** [comment]
I didn't know that the same file could work in two versions of minecraft

**Comment by Sollace** [comment]
> I didn't know that the same file could work in two versions of minecraft

Mostly they don't, at least across major releases, but 1.17 to 1.18 seems to have been a special case where there hasn't really been that much that's changed from a client's perspective, so a surprising amount of client-only mods will work on both 1,17 and 1.18.

**Comment by xanthian** [comment]
> > I didn't know that the same file could work in two versions of minecraft
> 
> Mostly they don't, at least across major releases, but 1.17 to 1.18 seems to have been a special case where there hasn't really been that much that's changed from a client's perspective, so a surprising amount of client-only mods will work on both 1,17 and 1.18.

And there are no MC versions defined in the mod dependencies for this..

**Comment by Degostor** [comment]
ooo
