### ISSUE TITLE
[Suggestion/Bug] Particle only Allay trails / Allay trails render around crosshair with shaders

### ISSUE THREAD

**Issue by JLUsr** [Ladysnake/Effective#190]
This is just a suggestion about making the `Enable Allay trails` option have 3 options, `Yes`, `Particles Only`, and `No` instead of just `Yes` and `No`. I like the particles an Allay will produce when trails are enabled; however, the actual trail (for both Allay and Improved Spectral Arrows) can have some issues when shaders are enabled, where they sometimes render around the crosshair (see image), also, there is some personal bias here since I prefer the particles without the smooth trail (not that my personal preference should be a factor or anything though).

![image](https://github.com/Ladysnake/Effective/assets/47650360/3886ecbe-71ce-4d82-827b-328ed0466a67)

**Comment by doctor4t** [comment]
[5a185e6](https://github.com/Ladysnake/Effective/commit/5a185e6629765800086161938fa781fc5a393182)
