### ISSUE TITLE
"Glowing plankton"option is invalid

### ISSUE THREAD

**Issue by Miaochan** [Ladysnake/Effective#193]
There are no glowing plankton particles at night though I enable it
![2023-06-30_09 23 09](https://github.com/Ladysnake/Effective/assets/129179911/2062f792-5c8c-4f28-abb1-7b180bd6dded)

**Comment by doctor4t** [comment]
Glow plankton shows up on the surface. Makes splashes, ripples and cascade clouds glow blue.
