### ISSUE TITLE
Just waterfall and ripples

### ISSUE THREAD

**Issue by Visitor2579** [Ladysnake/Effective#20]
Mod seem to have no spash model of water nor lava showing up when it should like showcased in video of this mod, its just ripples and little water particles. Waterfall is extreamly loud and has no water particles going down but it has those particles which look like camp smoke. But it's still amazing keep up.. Would this work for shaders?

**Comment by doctor4t** [comment]
Are you sure the water is deep enough and you or the entity is falling fast enough?
For now Canvas and Iris don't work with the mod because they modify a method I use, but given I got a fix PRed the issue with Canvas should be fixed soon enough.

**Comment by soepie7** [comment]
I have no Canvas or Iris here in my modlist, but still no splashes. I tried it with 4-deep water, and dropping various entities from about 140 blocks high, both water and lava.

**Comment by doctor4t** [comment]
You'll need to have a deeper pool or drop from less blocks, since splashes depend on the speed you have once you're in the water. So if you're too fast and reach the end before the game can calculate your speed, splashes won't happen or will be flat.
