### ISSUE TITLE
1.19.3 Compatibility? 

### ISSUE THREAD

**Issue by bIankface** [Ladysnake/Effective#201]
I was wondering if there was an easy way if you could upgrade the 1.19.2 version of the mod to 1.19.3 without annoying any of the devs by simply changing some branches of code so I could do it myself. Great mod also :)

**Comment by GitsurferQwerty** [comment]
Maybe just any version in general?

**Comment by Goby56** [comment]
> I was wondering if there was an easy way if you could upgrade the 1.19.2 version of the mod to 1.19.3 without annoying any of the devs by simply changing some branches of code so I could do it myself. Great mod also :)

Try this: https://www.youtube.com/watch?v=GWB8loTTfw0

**Comment by bIankface** [comment]
> 

sadly this doesn't work probably due to to code reworking im assuming mojang altered inbetween 1.19.2-1.19.4 :(
thanks for the help tho!
