### ISSUE TITLE
Flickering rain ripples using Complimentary Shaders

### ISSUE THREAD

**Issue by yermachello** [Ladysnake/Effective#205]
Works fine without shaders.
![javaw_bcSzn5i3Tm](https://github.com/Ladysnake/Effective/assets/7390018/f44647ce-2528-428d-aab9-e288f4a2175b)
Stops flickering while moving.
![javaw_tQekPaFmPa](https://github.com/Ladysnake/Effective/assets/7390018/f9d1f3f5-5087-4b93-843a-85ae62d677de)

Minecraft 1.19.2
Quilt 0.19.2
Effective 2.1.1

**Comment by doctor4t** [comment]
Does this happen on the latest Fabric release?
