### ISSUE TITLE
Log spamming "false" when in a world.

### ISSUE THREAD

**Issue by Mabra51** [Ladysnake/Effective#208]
My logs are being spammed with the single word "false" whenever i join a world.

Minecraft version: 1.19.2

Mod version: 1.4

**Comment by Arathain** [comment]
fixed in latest 1.19.2 version

**Comment by Mabra51** [comment]
1.4 is the latest 1.19.2 version.

**Comment by Xiribidus** [comment]
Only on fabric, the newer versions are on quilt

**Comment by Razatop** [comment]
> 1.4 is the latest 1.19.2 version.

TLDR You won't be able to use Effective on 1.19.2 without the False spam unless you convert your modpack to quilt.
