### ISSUE TITLE
No cascade clouds in 1.18 using Sodium 0.4.0.alpha5

### ISSUE THREAD

**Issue by YurgenSchn** [Ladysnake/Effective#21]
Well, that's it really. There are splashing water particles in waterfalls, but no cascade clouds (visual particles nor sound).

I came to this conclusion by isolating all the mods but Effective + Sodium.

Also, without Sodium, or using Optifabric (works properly), cascade sounds are EXTREMELY LOUD, with an obnoxiously far range.

**Comment by Sollace** [comment]
Sodium incompatibility has already been reported in #5 and there is an open PR ( #17 ) that addresses it, though admittedly in a very blursed way.

The loud waterfalls have also been reported in #11
