### ISSUE TITLE
1.20/1.20.1 support

### ISSUE THREAD

**Issue by SlightlyPeckish** [Ladysnake/Effective#210]
As the title suggests, are there any plans for this to be updated to 1.20/1.20.1? I love the mod and would love to keep using it on 1.20

**Comment by Xiribidus** [comment]
[Please refer to the FAQ!](https://github.com/Ladysnake/Effective/blob/main/README.md#q-can-you-backport-this-mod-to-1x-when-will-you-update-to-1x)

**Comment by SlightlyPeckish** [comment]
My bad completely missed that

**Comment by Xiribidus** [comment]
nw
