### ISSUE TITLE
The Forge Issue.

### ISSUE THREAD

**Issue by ScriptKittyJane** [Ladysnake/Effective#214]
Not making a forge port for such a popular mod is kinda silly :/

Even with the listed reasons it doesn't make sense to punish the players who have to use forge.

**Comment by Arathain** [comment]
A forge port was made once, but the creator vanished off of the face of the earth. Is it "punishment" when you're not able to play a windows-based game on Mac? I don't think it is; choose your modloader and stick with it.
A port to forge OR fabric is not being made. Have a nice day / night / eternal twilight.
