### ISSUE TITLE
Is there a way to use the latest effective mod without switching all my mods to Quilt? 

### ISSUE THREAD

**Issue by g00berdawg** [Ladysnake/Effective#217]
I've searched up ways to get effective to work w/ Fabric mods many times but the only lead I got was the Quilted Fabric API and the Satin API. I'm still very confused

**Comment by UpcraftLP** [comment]
No, you will need to use quilt loader.

Fabric mods work on quilt, but not the other way round.

**Comment by Aces-and-Jacks** [comment]
This can be closed since an answer has been provided
