### ISSUE TITLE
Illuminations/Effective overhead pets being removed ?

### ISSUE THREAD

**Issue by deadtoxaris** [Ladysnake/Effective#219]
not mainly as "issue" but do overhead pets come with effective ? cuz when i go to dashboard i cant find the one i was using and also many others.. did you remove it on purpose or ? i paid for rank 2 i think and was using Founding Skull

**Comment by Xiribidus** [comment]
Added Illuminations cosmetics (though they may get removed or reworked in the future)

    Reworked the Will o' Wisp pet cosmetic to allow players to choose two custom colors to personalize their Will o' Wisp
    As a result, Golden Will and Founding Skull cosmetics were removed as they can be replicated with custom colors

^is what the changelog says, if anything else is missing please tell us

**Comment by deadtoxaris** [comment]
is there a way to bring them back, thru mod assets and changing some textures ? probably will try to do it anyway, cuz idk what changing color does, i put different colors and it kind of changed the pet but not the color.. meh amma see what i can do with that, but thanks for response tho
