### ISSUE TITLE
Needs to be on Fabric and not Quilt

### ISSUE THREAD

**Issue by ebaystudio** [Ladysnake/Effective#222]
Such a shame the dev burned this mod to the ground. Quilt only, really....

**Comment by Pyrofab** [comment]
"The Dev" did not burn Effective to the ground, but staying on Fabric certainly would have. And considering 95% of mods work on Quilt, I fail to see a compelling reason not to make the move really.

**Comment by ebaystudio** [comment]
Oh really. Let's look at the numbers. 
Fabric Downloads 4,5 Million.
Quilt Downloads 345 thousand.

**Comment by SekoiaTree** [comment]
1. this is already refused in the FAQ
2. the old versions still exist. The devs decide what they want to do with *their* mod
3. even if they *wanted* to switch back, a dependency they didn't make depends on quilt, so they couldn't

If you look at the closed issues, there are tons of *this exact issue*. Stop it, and read the FAQ.

**Comment by ebaystudio** [comment]
Surprised he hasn't pulled it actually. He does love to virtue signal. 

Like I said he burned it to the ground and it's a shame he couldn't dissociate from some online drama and worse yet associate with a worse group of people. Its shameful

And the dependency excuse is just that an excuse we both know it can be developed without it. It uses the Quilt API, Fabric API will work fine. And Satin API works with Fabric so yeah. 

Said my peace and I'm sure you'll hide my replies. It's just a real shame, this "WAS" a really great addition to Minecraft and added so much to the game. But like you said you can do whatever you want with it.

**Comment by Pyrofab** [comment]
Okay, I get it now. You are free to refuse to install the mod for ideological reasons, but please refrain from making it our problem.
