### ISSUE TITLE
[Feature Request] Armor Shine

### ISSUE THREAD

**Issue by DarkcrossPrime** [Ladysnake/Effective#224]
I saw an other mod have this but i think it would be neat for some shiny/reflective blocks or items to have a particle effect around them when exposed to a certain amount of light. Here's an example :

![Capture](https://github.com/Ladysnake/Effective/assets/76731934/c37e468e-277a-441f-a094-50df852a2d1d)

**Comment by GitsurferQwerty** [comment]
The mod "Visuality" already does this.

**Comment by DarkcrossPrime** [comment]
> The mod "Visuality" already does this.

yeah but it would be nice to have all of those things in one mod

**Comment by Arathain** [comment]
already exists in another mod and would be a pain to do any better - I'll take the liberty to close this one
