### ISSUE TITLE
Allow Ports To Other Modloaders

### ISSUE THREAD

**Issue by peepeepoopoocaca** [Ladysnake/Effective#226]
Nobody uses Quilt and gatekeeping mods is cringe.

**Comment by peepeepoopoocaca** [comment]
That's craaaaaazy. Actually so cringe

**Comment by randomcoder67** [comment]
Someone should just fork it, it's open source. 
Trying to gatekeep it is entirely against the point of being open source, especially when  done for ideological reasons.

**Comment by UpcraftLP** [comment]
> it's open source.

[Is it?](https://github.com/Ladysnake/Effective/blob/736433b096dcd561d70a5f737a787a3c7e891d0c/LICENSE)

**Comment by eczy-eclipse** [comment]
> Someone should just fork it, it's open source. 

Software being open source doesn't mean that you automatically have the right to fork & redistribute. 

You might be thinking of [FOSS](https://en.m.wikipedia.org/wiki/Free_and_open-source_software).

**Comment by randomcoder67** [comment]
> > it's open source.
> 
> [Is it?](https://github.com/Ladysnake/Effective/blob/736433b096dcd561d70a5f737a787a3c7e891d0c/LICENSE)

I can see the source code, so yes

**Comment by randomcoder67** [comment]
> > Someone should just fork it, it's open source.
> 
> Software being open source doesn't mean that you automatically have the right to fork & redistribute.
> 
> You might be thinking of [FOSS](https://en.m.wikipedia.org/wiki/Free_and_open-source_software).

It means you have the ability to. When it comes to software I don't really care if someone says you don't have the "right" to do something, especially when it's being enforced for political reasons.

**Comment by eczy-eclipse** [comment]
> It means you have the ability to.

You have the ability to do many things that can get you in legal trouble. I don't see your point. 

Either do it and see what happens or stop complaining, lol

**Comment by randomcoder67** [comment]
> > It means you have the ability to.
> 
> You have the ability to do many things that can get you in legal trouble. I don't see your point.
> 
> Either do it and see what happens or stop complaining, lol

The point is placing restrictions on how people can fork your mod because of political reasons is a) very cringe and b) destructive to the modding community
