### ISSUE TITLE
Sinytra Connector Compat Sugestion

### ISSUE THREAD

**Issue by ChromeTV** [Ladysnake/Effective#228]
Recently, there is a Forge layer mod called "sinytra connector" (https://modrinth.com/mod/connector) that allows fabric mods to run in the Forge mod loader. 
I'm wondering if it's possible to make Effective compatible with that when it's ported to 1.20?

I consider that it would greatly facilitate the issue of compatibility between fabric/forge/quilt in a single build using that layer.

**Comment by Arathain** [comment]
No Forge/Fabric compatibility in any form will be considered, implemented, or maintained - it is, as the pinned issue indicates, unsupported, and remains so for the foreseeable future.
