### ISSUE TITLE
fabric?

### ISSUE THREAD

**Issue by UnknownSkid** [Ladysnake/Effective#230]
didnt this mod work on fabric?

**Comment by Aces-and-Jacks** [comment]
Look on issues before you ask. There's already a pinned issue that asks about fabric. The creator is only supporting quilt and has no plans to switch back to fabric. This issue can be closed

**Comment by UpcraftLP** [comment]
![image](https://github.com/Ladysnake/Effective/assets/10714589/f9fde877-c217-4867-9208-b148644a5ba5)
