### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by kittenvr** [Ladysnake/Effective#231]
is there gonna be a port to 1.20.4, if not is there a fork that has done this?

**Comment by DrKoneko** [comment]
bump, would also like to know. I just looked through for a few minutes and haven't found anything relating to anyone updating it to 1.20.4 but I could have missed something.

**Comment by meowinqq** [comment]
bump, same reason as above :')!!

**Comment by zeussesions** [comment]
bump!!

**Comment by Xiribidus** [comment]
bump, I have yet to see a pull request of anyone trying to update effective to 1.20.4 but people are of course free to try, as for official ports please refer to RATs FAQ at the bottom of the [modrinth page](https://modrinth.com/mod/effective)
