### ISSUE TITLE
Effective 1.4 crashes with Satin 1.9.1 On Minecraft version 1.19.2

### ISSUE THREAD

**Issue by Fade-Alchemist** [Ladysnake/Effective#234]
https://github.com/Ladysnake/Satin/issues/44#issue-2063132912

Copy from Satin's bug tracker

While using Minecraft 1.19.2 and Fabric 0.14.24, Effective 1.4 paired with Satin 1.9.1 will crash with error code 1 on startup.
Satin 1.9.0 paired with Effective 1.4 does not crash and starts correctly

The crash and log files are attached.

[crash-2024-01-02_11.55.52-client.txt](https://github.com/Ladysnake/Satin/files/13815023/crash-2024-01-02_11.55.52-client.txt)
[2024-01-02-2.log.gz](https://github.com/Ladysnake/Satin/files/13815028/2024-01-02-2.log.gz)

**Comment by Sunconure11** [comment]
Can confirm the same issue.

**Comment by Pyrofab** [comment]
Marked the Satin version as beta, since it seems to cause trouble in most cases
