### ISSUE TITLE
Error when using this mod on a LAN server

### ISSUE THREAD

**Issue by DarkFireNinja** [Ladysnake/Effective#235]
When i try to use this mod on a LAN server with my brother who doesn't have the mod installed (he is using Vanilla Minecraft), he gets this error when he tries to join my world:

**Connection Lost

Unsupported (vanilla?) client!
This server requires modded client to join!**

I'm using Quilt Loader on version 1.20.1 of Minecraft.

**Comment by doctor4t** [comment]
I don't know much about LAN, does this still happen on the latest Fabric release?
