### ISSUE TITLE
[Feature Request] Config entry to adjust water fall height for cascades.

### ISSUE THREAD

**Issue by GillianGroks** [Ladysnake/Effective#237]
While I love the cascade feature, sometimes terrain (cave) generation can create flowing water underneath areas in villages or other structures, and you end up with cascades in places they wouldn't be naturally.

If there was a way to check Y value distance from the original source block, and only spawn cascades at a configurable distance we could keep this from happening. Possibly an integer value from 1-15?

This screenshot is from water flowing down 1 block under a village farm:
![Farm Cascades](https://github.com/Ladysnake/Effective/assets/36685783/dce6ff02-1c85-4f83-b6ed-2efd63fa8f51)

**Comment by doctor4t** [comment]
I really wanna get those pesky "mini-cascades" at some point, but I'm not too fond of making it a config, I'd much rather it being a better algorithm to detect them haha, I'll keep brainstorming
