### ISSUE TITLE
Parry Flash

### ISSUE THREAD

**Issue by eightbitgiraffe** [Ladysnake/Effective#239]
Honestly, I love Ultrakill so much, and the parry freeze thing this mod adds is amazing (along with all the other features, of course.) However, one feature I wish was here was the white flash when you parry an attack, maybe some additional light added to the world. I would just implement this myself but I have no understanding of anything Java related and I apologize for that, but I assume it isn't too difficult to add.
Either way, thank you for such a great mod!

**Comment by Pyrofab** [comment]
the white flash is in fact supposed to exist, it was however lost in the 1.20 update because of a bug in the underlying library

**Comment by doctor4t** [comment]
Duplicate of #253
