### ISSUE TITLE
Neoforge?

### ISSUE THREAD

**Issue by Nicodemus111** [Ladysnake/Effective#240]
I agree with the decision to stop supporting fabric/forge but like is neoforge a consideration? I definitely do not have the skill to port it myself but maybe someone else could if it was allowed?

**Comment by Xiribidus** [comment]
Only @doctor4t can ultimately answer this I guess (I'll try adding the answer to FAQs in the future)

**Comment by ToppyTopology** [comment]
hello, is there an update if this is still being considered? I support the forks and the use of modrinth aswell, though a port for the neoforge modloader should reach more players in the future with a good set of developers working behind it

**Comment by doctor4t** [comment]
I'm not considering porting to any other loaders, but I welcome anyone who would like to do so to join the Ladysnake Discord and get permission there.
