### ISSUE TITLE
Baked chest models from Enhanced Block Entities are invisible

### ISSUE THREAD

**Issue by SPINZ1** [Ladysnake/Effective#244]
When using the Enhanced Block Entities mod, with enhanced chests enabled, chest, trapped chest, and ender chest models are invisible.

https://github.com/Ladysnake/Effective/assets/145732023/eea8c34b-6263-40c8-9765-1948055f5ff3

**Comment by doctor4t** [comment]
Effective doesn't touch the rendering of chests at all, only hooks into the opening animation for bubble spawning underwater, what makes you think this is Effective's fault?

**Comment by Dashy22** [comment]
I tried it alone with just effective and the enhanced block entities and it works fines, I also tried a few other big performance and helpful mods and it still works.
Chests looked fine to me I think it's just a video problem 

https://github.com/user-attachments/assets/2600f478-c9b0-47d8-ac9e-a2c4e07795b6
