### ISSUE TITLE
Crash on startup with only Effective and dependencies on Quilt 1.19.2 (Caused by: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: shaders/core/lodestone:particle.json)

### ISSUE THREAD

**Issue by Aquaeyes** [Ladysnake/Effective#247]
effective 2.1.1+1.19.2
midnightlib 1.0.0 
satin 1.9.1
qsl beta.29_fapi-0.77.0
Quilt Loader 0.24.0

(Caused by: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: shaders/core/lodestone:particle.json)
[latest-5.log](https://github.com/Ladysnake/Effective/files/14533034/latest-5.log)

The same issue also occurs without midnightlib.

**Comment by Syclusion** [comment]
A shame this seems mothballed in 1.19.2 as its been 2 weeks with silence of the mod being completely unusable in this version

**Comment by Pyrofab** [comment]
Hello, could you try with the latest *non-alpha* version of Satin API ? Like 1.9.0

**Comment by Aquaeyes** [comment]
Such works! You also need to update QSL to the latest version for Satin to not crash with 
[crash-2024-03-27_20.46.47-client.txt](https://github.com/Ladysnake/Effective/files/14773587/crash-2024-03-27_20.46.47-client.txt) - qfapi-4.0.0-beta.29_qsl-3.0.0-beta.29_fapi-0.75.1_mc-1.19.2.jar.

**Comment by Aquaeyes** [comment]
(Ack, apologies)

**Comment by ff6f8d68** [comment]
same error but with QSL on newest version

**Comment by retropele** [comment]
I'm also getting this error with QSL latest version and Effective. It's the best mod ever, so it's a shame, but no stress, you've a lot going on.

But it is the ultimate luxury mod! Is there a version we can roll back to for the time being?

**Comment by doctor4t** [comment]
Moved to Fabric, Quilt version will no longer be supported
