### ISSUE TITLE
Incompatible With Embeddium

### ISSUE THREAD

**Issue by PolyframeX** [Ladysnake/Effective#249]
Using embeddium on 1.20.1 causes the game to crash.

Minecraft: 1.20.1
Quilt: 0.24.0
QFAPI: 7.5.0
QSL: 6.1.2

Effective: 2.2.1
Embeddium: 0.3.11

Logs: [crash-2024-03-30_18.05.46.7076-quilt_loader.txt](https://github.com/Ladysnake/Effective/files/14813469/crash-2024-03-30_18.05.46.7076-quilt_loader.txt)

Note: Other mods are installed in the used log, however this issue is reproducable with only Effective and Embeddium.

**Comment by eczy-eclipse** [comment]
Is there any reason for using Embedium (fabric mod) instead of Sodium for Quilt? Genuine question.

**Comment by BlueJayofEvil** [comment]
> Is there any reason for using Embedium (fabric mod) instead of Sodium for Quilt? Genuine question.

It retains the optional use of the compact vertex format (that Sodium removed due to compatibility issues) and offers an optional method of translucency sorting (that Sodium doesn't have yet.)

**Comment by OlaPessoa** [comment]
> Is there any reason for using Embedium (fabric mod) instead of Sodium for Quilt? Genuine question.



> > Is there any reason for using Embedium (fabric mod) instead of Sodium for Quilt? Genuine question.
> 
> It retains the optional use of the compact vertex format (that Sodium removed due to compatibility issues) and offers an optional method of translucency sorting (that Sodium doesn't have yet.)

also, adding to what bluejayofevil said, i'll also make a genuine question, aside of the whole childish drama, is there any actual and reasonable REASONS to leave fabric and go to QUILT? Fabric had a wish version as a son, his name is QUILT
ffs

**Comment by sorae42** [comment]
> > Is there any reason for using Embedium (fabric mod) instead of Sodium for Quilt? Genuine question.
> 
> > > Is there any reason for using Embedium (fabric mod) instead of Sodium for Quilt? Genuine question.
> > 
> > 
> > It retains the optional use of the compact vertex format (that Sodium removed due to compatibility issues) and offers an optional method of translucency sorting (that Sodium doesn't have yet.)
> 
> also, adding to what bluejayofevil said, i'll also make a genuine question, aside of the whole childish drama, is there any actual and reasonable REASON to leave fabric and go to QUILT? Fabric had a wish version as a son, his name is QUILT ffs

I'm not a fan of this change either, but you are clearly being annoying and did not read the README and the pinned issue.
If you protest their decision, just make yourself a mod like this without using their assets and anyone will be happy.

_"ffs"_

**Comment by UpcraftLP** [comment]
Fixed in embeddium 0.3.18

**Comment by vinnyg0621** [comment]
> Is there any reason for using Embedium (fabric mod) instead of Sodium for Quilt? Genuine question.

it's Embeddium not Embedium.
