### ISSUE TITLE
Possible workaround for a distance requirement for when the waterfall effect starts

### ISSUE THREAD

**Issue by Corvus20** [Ladysnake/Effective#25]
I noticed in the showcase video for this mod that all waterflow, no matter how small, would have the waterfall effects. I think that OreCruncher's Dynamic Surroundings mod (https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-fabric-edition) may have the solution to the problem. Its waterfall sounds require the water flow to be falling from a certain height in order to create the sounds, and it is client side + server friendly. I don't know if there is some other limitation or something I am just not aware of, but I figured it would still be worth mentioning just in case.

**Comment by ClientCrash** [comment]
Couldn't you just check if there are at least 2 flowing water blocks above one water source block?

**Comment by Corvus20** [comment]
I am assuming that is how dynamic surroundings does it.
