### ISSUE TITLE
1.19.2 version is incompatible with latest QFAPI.

### ISSUE THREAD

**Issue by sisby-folk** [Ladysnake/Effective#250]
QFAPI updated to include fapi 0.77 in march in `4.0.0-beta.30+0.77.0-1.19.2`.

Effective crashes on it, like so:

https://mclo.gs/QxDkhYJ

**Comment by UpcraftLP** [comment]
Known issue, sadly the current best solution is to downgrade QFAPI.

**Comment by sisby-folk** [comment]
latest create requires 77, so we've removed effective instead in our case - cheers for the clarification though!

**Comment by UpcraftLP** [comment]
If it doesnt absolutely need that version you could also try dependency overrides to make create accept an older version of fabric api

**Comment by sisby-folk** [comment]
preferring to stay on the side of packwiz modpack stability - if we're on 77, the pack is less likely to break at random from a mod bumping their dep later.

**Comment by unilock** [comment]
Effective JiJ's an outdated version of Satin API; the latest version for 1.19.2 ([v1.9.1](https://modrinth.com/mod/satin-api/version/1.9.1)) fixes running alongside Fabric API v0.77.0. It's possible to just install that version of Satin API manually, alongside Effective, to have Quilt Loader favor the newer version over the JiJ'd one.

**Comment by UpcraftLP** [comment]
> Effective JiJ's an outdated version of Satin API; the latest version for 1.19.2 ([v1.9.1](https://modrinth.com/mod/satin-api/version/1.9.1)) fixes running alongside Fabric API v0.77.0. It's possible to just install that version of Satin API manually, alongside Effective, to have Quilt Loader favor the newer version over the JiJ'd one.

does it now, huh?
It used to cause the opposite, that's why it is marked as alpha.

**Comment by UpcraftLP** [comment]
So after doing a few more tests on this:
- on fabric you can only use up to Effective `1.4`, but that version works fine with latest satin + FAPI.
- on quilt you can use the latest versions of Effective (`2.0` and later), however they do not work with Satin `1.9.1` at all (you must use `1.9.0`), and also do not work with latest QFAPI, only up to `4.0.0-beta.30+0.76.0-1.19.2`.

So I dont know how exactly you got it to work with latest @unilock?

**Comment by unilock** [comment]
I'm sorry, I just tested QFAPI 0.77.0 + Effective 2.1.1 + Satin 1.9.1 and can confirm, it does not work. I'm not sure why I thought otherwise...

I guess Lodestone also has to be updated for the changes in Fabric API 0.77.0?
