### ISSUE TITLE
embedded mod "lodestonelib" crash

### ISSUE THREAD

**Issue by PikachuGabe** [Ladysnake/Effective#254]
Minecraft: 1.20.4
Quilt: 0.24.0
QFAPI: 9.0.0-alpha-7+0.96.11
QSL(embeded in QFAPI): 8.0.0-alpha.12+1.20.4
Efective: 2.2.1

[crash-2024-04-16_19.26.58.3496-quilt_loader.txt](https://github.com/Ladysnake/Effective/files/15004153/crash-2024-04-16_19.26.58.3496-quilt_loader.txt)
i found the lines that are erroring in lodestone-refmap.json, those being line 47 and line 106. cant pretend i understand the error, but i know it can prob be dealt with

**Comment by UpcraftLP** [comment]
![image](https://github.com/Ladysnake/Effective/assets/10714589/6b85d6a2-1c8d-44da-b608-3645548c7d76)
