### ISSUE TITLE
1.20.4 Fabric possible?

### ISSUE THREAD

**Issue by EfficientStinkbug** [Ladysnake/Effective#255]
Sorry for opening an issue, but would you consider porting it to 1.20.4 fabric?
This mod adds so much ambience. I used the "illuminations" part of it on 1.12.2 and am really missing it now.

**Comment by Xiribidus** [comment]
There won't be any new fabric versions, check #134 and the [effective FAQ](https://modrinth.com/mod/effective) for more info.
