### ISSUE TITLE
Someone should probably update this

### ISSUE THREAD

**Issue by Crappy-Productions** [Ladysnake/Effective#257]
![Screenshot_20240526_160930_Chrome](https://github.com/Ladysnake/Effective/assets/98716926/635940b9-abfd-4eee-afac-e3529a682027)

**Comment by Xiribidus** [comment]
The effective wiki is generally outdated, currently working on Rat's Mischiefs wiki but that's one of the next things. In the meantime: [PR89](https://github.com/Ladysnake/Ladysnake.github.io/pull/89)
