### ISSUE TITLE
[Suggestion] Put older versions on Modrinth

### ISSUE THREAD

**Issue by SamHammie** [Ladysnake/Effective#258]
### Mod Loaders

Fabric, Quilt

### Minecraft Versions

1.18.1, 1.18.2, 1.19, 1.19.1, 1.19.2

### Mod Versions

1.0, 1.1, 1.1.1, 1.2, 1.2.1, 1.2.2, 1.3, 1.4, 1.4.1, 1.5, 1.6

### Suggestion

It'd improve my quality of life, and I'm sure the quality of life of many others, if you'd add the mod versions prior to Effective version 2.0 for Minecraft version 1.19.2 to your Modrinth release page for Effective.

**Comment by Xiribidus** [comment]
You don't have to open an issue for every single repo, we got the message

**Comment by SamHammie** [comment]
Apologies, you are correct. I just wanted to be thorough. Thank you for taking a look at my requests.

**Comment by EfficientStinkbug** [comment]
the mod is basically dead and the devs don't care

**Comment by NolanHewitt** [comment]
> the mod is basically dead and the devs don't care...or so I thought, because a new update has come out for a fabric 1.18 version, I'm hyped for the future :o

That's an old version from curseforge re-uploaded to modrinth, not a new version. If a new version of the mod was made it would be for newer version of the game, not 1.18

**Comment by doctor4t** [comment]
Some old versions were posted on Modrinth for 1.18

**Comment by Xiribidus** [comment]
Oh yeah, ran into an issue with uploading the rest that I couldnt solve at the time, might try again
