### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by Soabac** [Ladysnake/Effective#263]
title, no pressure tho :D

**Comment by GavinGoGaming** [comment]
Im **trying** to make a WIP 1.21 port [here](https://github.com/gavingogaming/effective-1.21), help wanted as im not a gradle person and dont really know how gradle libs work (i use maven as i come from the plugin community)

**Comment by Soabac** [comment]
wait so what ? you're saying you've (sorta) made the 1.21 version but there's only the gradle missing ?

**Comment by GavinGoGaming** [comment]
I'm trying to retrace the steps used in the 1.19 -> 1.20 update but for 1.20 -> 1.21. This has a high chance of failing cuz some ladysnake libraries havent been updated but are used by effective, and 1.20.6 completely remade the data system with "components". Dont expect much from this port - its a mediocre attempt

**Comment by Soabac** [comment]
oh alright, good luck tho! seems interesting. i wish i knew how to code and stuff to do things like this

**Comment by au5ton** [comment]
Recent commit https://github.com/Ladysnake/Effective/commit/97263886223ecd6725c877ba56461aa24bf04573 suggests that the mod is waiting for the following projects to update to 1.21 (which are under active development):
- https://github.com/LodestarMC/Lodestone
- https://github.com/FoundryMC/Veil

**Comment by GavinGoGaming** [comment]
Yeah - thats why i paused on my port, some of the libraries needed just arent updated (lodestone, veil, and at the time of making the port, one other gradle thing)

**Comment by doctor4t** [comment]
Will happen in due time, waiting on Lodestone and Veil as previously mentioned by other users.
