### ISSUE TITLE
Missing files and shit

### ISSUE THREAD

**Issue by Someminecraftdudethatismad** [Ladysnake/Effective#264]
[13:49:06] [main/ERROR]:
 Registry 'blabber:dialogue_actions' was empty after loading
[13:49:06] [main/ERROR]:
 Registry 'requiem:mob_actions' was empty after loading 
 Is always what I get when I load one of their mods, which is annoying (Modrinth)

**Comment by mikidomikari** [comment]
Don't even bother reaching out or necro-posting. Ladysnake dev team are virtue-signaling trans 'allies' who care more about how people think of them and their half-assed code than the trans community itself. As soon as I heard of this nonsensical laziness I began replicating the mod exactly for Fabric, I'll be finished porting soon, too, and posting it to github - mostly out of spite at this point - and if they or their legal doesn't like that then I'll just post it somewhere else as a torrent. Love you Ladysnake! I'm trans btw <3

**Comment by Pyrofab** [comment]
To answer the original question, Blabber and Requiem are not included in Effective, so this issue would belong to the Requiem or Blabber repository. It is however not exactly a mod issue and more of a harmless mojang oversight that disappears in later versions of the game.

As for the other comment, sorry to disappoint but if your goal as a modder is to get the smallest number of assholes coming at you, openly supporting trans rights is not the way to do it. And I'm not sure what you are specifically calling out when you say laziness, but I think most of us in the team would call it having a life outside Minecraft. You may want to consider that this kind of comment is not exactly helping our motivation either.

We of course welcome your continued support and respect for our work, and hope our "legal" (that is, ourselves) won't have to reach out to you for such unenjoyable matters as copyright infringement.
