### ISSUE TITLE
Crash on World Creation(2.3)

### ISSUE THREAD

**Issue by NotAPotter** [Ladysnake/Effective#266]
Crash Report:
[crash-2024-09-20_16.17.49-server.txt](https://github.com/user-attachments/files/17080458/crash-2024-09-20_16.17.49-server.txt)
Log:
[latest.log](https://github.com/user-attachments/files/17080460/latest.log)

**Comment by doctor4t** [comment]
You're not supposed to put the mod on the server, it's a client-side only mod

**Comment by NotAPotter** [comment]
I don't know what to do with that info, I've heard these terms before but they've never made a difference before.

**Comment by Xiribidus** [comment]
Wdym never made a difference? Practically, you should remove effective from the server entirely and have the players download it only

**Comment by NotAPotter** [comment]
There are no other players but me.
