### ISSUE TITLE
[Feature Request] Lowering Volume of animals in ambience.

### ISSUE THREAD

**Issue by Dashy22** [Ladysnake/Effective#269]
I would like a way to lower specific ambiences, mostly just the creature ambiences, like the birds and crickets. But for other people you could add more configuration possibilities.

` I don't like ambience mods because they add crickets and birds that aren't actually there, but I do like most other ambiences added here.`

**Comment by doctor4t** [comment]
Plan is for the audio to be dynamic and multi-layer depending on where you are, so I can totally see a few sliders to adjust wind volume, animal volume, etc...

**Comment by doctor4t** [comment]
Done in latest release
