### ISSUE TITLE
[Feature Request] Vanilla Music gets slightly muffled if underwater or in a really deep cave 

### ISSUE THREAD

**Issue by Dashy22** [Ladysnake/Effective#271]
Might not be the best feature request but it would be cool.
Maybe when underwater it would also slightly muffle other sounds but I think that the music muffling would be the nicest.
And for the cave idea, I feel you would have to be below -30 to start being muffled and it shouldn't be as noticeable as water.

**Comment by doctor4t** [comment]
I don't really wanna touch the way music works already, I feel like it would be hell. It's a fun idea though! Just not one I'm willing to implement

**Comment by Dashy22** [comment]
Ok! Thanks for being nice about it
