### ISSUE TITLE
Crash on startup with Embeddium

### ISSUE THREAD

**Issue by restlessPik** [Ladysnake/Effective#273]
Embeddium casues the game to crash on startup

Game version: 1.20.1
Loader: Fabric 0.16.5

Mods:

Effective 2.3.2
Embeddium 0.3.25
Fabric API 0.92.2

Log: [crash-2024-09-27_12.03.44-client.txt](https://github.com/user-attachments/files/17166237/crash-2024-09-27_12.03.44-client.txt)

**Comment by Poopooracoocoo** [comment]
https://github.com/LodestarMC/Lodestone/issues/46#issuecomment-2358866532

**Comment by restlessPik** [comment]
Come to think of it I don't know why I still use embeddium instead of sodium haha. You should probably say it's incompatible somewhere on the mod page, I think many people use that mod over sodium.

**Comment by doctor4t** [comment]
No Lodestone from now on, so this should be fixed
