### ISSUE TITLE
Backport for sodium 0.5.8 perhaps?

### ISSUE THREAD

**Issue by Yum-Muy** [Ladysnake/Effective#275]
I've tried every current version for 1.20.1, but none seem to work with F.O and sodium to 0.5.8 (along with its mods that it uses) so that it could be allowed to be used with Nvidium.

**Comment by KarmaMarazu** [comment]
> I've tried every current version for 1.20.1, but none seem to work with F.O and sodium to 0.5.8 (along with its mods that it uses) so that it could be allowed to be used with Nvidium.

im looking for this too! (but then for voxy (one of cortex's other mods))

**Comment by Poopooracoocoo** [comment]
Why not use Sodium 0.5.11? You can update other mods and create a dependency override. Anything in particular that doesn't work?

**Comment by KarmaMarazu** [comment]
> Why not use Sodium 0.5.11? You can update other mods and create a dependency override (or edit Nvidium's fabric.mod.json after opening its jar in 7-zip)

Yes this does work for nvidium (take the 0.2.7 for 1.20.6 should work) however it does not for voxy the 1.20.1 built is only on the discord and does not work with a simple overwrite on sodium 0.5.9 and above sadly

**Comment by Armdndnagerpfish36** [comment]
Also you cant use this with immersive portals and sodium (which is pretty annoying).
