### ISSUE TITLE
Porting Permission Request?

### ISSUE THREAD

**Issue by ConcerroX** [Ladysnake/Effective#279]
Since there isn't a port that supports Forge/NeoForge 1.20.1 without Sinytra Connector yet, may I get permission to create it?

**Comment by ConcerroX** [comment]
Is anyone here? 🤔

**Comment by JK82NL** [comment]
The answer is actually on the mods description page.

> 
Q: Can I port this mod to Forge / Fabric?
A: No. I am not comfortable with ports of my mod being made for other loaders I do not wish to support, for the reason listed above.
>

**Comment by Poopooracoocoo** [comment]
@JK82NL The CurseForge description is outdated. Refer to the Modrinth page: https://modrinth.com/mod/effective

 > Q: Can I port this mod to [Loader]? Can I update this mod this mod to [Newer version]?
A: If you want to make a port or update of Effective, you are welcome to ask [in the Ladysnake Discord](https://discord.com/invite/RBHY26t) to get permission or [make a pull request on GitHub](https://github.com/Ladysnake/effective).

**Comment by JK82NL** [comment]
@Poopooracoocoo I did not realize that opinion changed over there. At least now @ConcerroX  got an answer.

**Comment by doctor4t** [comment]
If you are willing to maintain a NeoForge port of the mod, you are free to make a branch and then open a pull request. If it's good, I'll merge it and publish it officially.
