### ISSUE TITLE
[Suggestion] Make splashes respect water color

### ISSUE THREAD

**Issue by DarianLStephens** [Ladysnake/Effective#28]
Currently, splashes are a singular, universal color.
This looks pretty weird in water that doesn't match:
![2021-12-18_14 38 07](https://user-images.githubusercontent.com/15375876/146627687-944ffc79-9019-44ff-ae87-6819294863a0.png)

If the splash could be made to match the color of the water it's on, that could improve it quite a bit.

**Comment by MarkinhosMLP** [comment]
up

**Comment by lonefelidae16** [comment]
Sorry for the delay in replying.

I’ve been thinking about this nice issue for a long time and finally was able to reflect the color of the water based on the biome.

![2022-09-14_17 36 21](https://user-images.githubusercontent.com/74746227/190112920-6ddf88dc-2289-4cee-b47a-032c4363034b.png)

The original texture must be separated into two parts: white and overlay, like potions.

And it also have a problem; looks darker than the original texture.

I’d like to submit a new PR when the color tone and brightness appear the same as original.
