### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 12Fate12** [Ladysnake/Effective#284]
[crash-2024-12-12_21.05.32-server.txt](https://github.com/user-attachments/files/18115850/crash-2024-12-12_21.05.32-server.txt)

**Comment by doctor4t** [comment]
This is a client side mod, don't put it on the server

**Comment by Pyrofab** [comment]
(the Quilt metadata was missing the bit that prevented the mod from being loaded on the server, this should now be fixed)
