### ISSUE TITLE
Waterfall Sound is way too loud

### ISSUE THREAD

**Issue by MilesBenjamin** [Ladysnake/Effective#3]

**Comment by camocreepercast** [comment]
Completely agree, it would be nice to be able to change its volume.

**Comment by jak3z** [comment]
> Completely agree, it would be nice to be able to change its volume.

the sounds make part of the ambient sounds so you can change, but on my tests i cannot makes less loud, only mute i guess

**Comment by spiralhalo** [comment]
Changing ambient sound volume works for me, 10% is pretty comfortable. It also affects swimming sounds though so not a permanent solution.

**Comment by RyanCR03** [comment]
im pretty sure effective plays the cascade sound every tick.
if you go near a cascade and check your sounds with F3 you'll notice that the cascades are causing an absurd amount of sounds
