### ISSUE TITLE
splashes dont work on waterlogged blocks

### ISSUE THREAD

**Issue by jamson-xu** [Ladysnake/Effective#30]
im not sure if this is a bug with other mods
heres my mod list
![image](https://user-images.githubusercontent.com/74874572/146697662-3efff67c-78ef-4aa3-a6c5-f1b98482b228.png)
it doesnt work on blocks that can be walked through in the water mainly

**Comment by Vextrove** [comment]
I **_strongly_** recommend using Starlight, it is 2937% faster than Phosphor.
