### ISSUE TITLE
Horrible performance when using optifine's internal shaders

### ISSUE THREAD

**Issue by Mouker-H** [Ladysnake/Effective#33]
Hello, I was playing with this mod installed. It would work just fine until I unloaded a chunk with a waterfall and then reloaded it. My game would become incredibly laggy and borderline unplayable. Is there anyway this mod could be optimized in the future?

Thanks,

**Comment by DimetryBadcoder** [comment]
Here you can find a link to a fixed version: 
https://github.com/Ladysnake/Effective/pull/24

Soon it should be updated officially, I guess
