### ISSUE TITLE
Too Many Lava Splashes. 

### ISSUE THREAD

**Issue by JustAHuman-xD** [Ladysnake/Effective#37]
When an item or entity goes into lava there are too many splashes. Instead of just one it makes one for everyone time its colliding with the lava. 
Im using Fabric Loader 0.12.12 with the latest update for fabric API
For ex:

https://user-images.githubusercontent.com/65748158/147417807-7d829034-2245-45d1-a3f4-16c8b999e31e.mp4

**Note i did test it without item physics and there was no difference**

**Comment by JustAHuman-xD** [comment]
Also I tested it on the fabric loader 0.12.11 and this was not an issue, it only happens on 0.12.12

**Comment by JustAHuman-xD** [comment]
If you would like me to give my mod list I can

**Comment by BravelyPeculiar** [comment]
Related: when Striders walk on the surface of lava, they cause continuous splashes every frame

**Comment by Visitor2579** [comment]
Very much the same here + lava splashes appear continuously and not even in lava, when you are on egde to lava and start to jump it splashes

**Comment by MarkinhosMLP** [comment]
up
