### ISSUE TITLE
[Feature Request] Cascade volume control

### ISSUE THREAD

**Issue by BravelyPeculiar** [Ladysnake/Effective#39]
The cascade sound is quite loud, and it'd be nice if players had the option to turn it down to be more subtle / less distracting

**Comment by MarkinhosMLP** [comment]
up

**Comment by Boy0000** [comment]
Was gonna come and mention this. It is currently waaay to loud to the point i have to mute the entire game.
Volume control would indeed be nice

**Comment by wackoamd1** [comment]
i agree , to loud sounds

**Comment by Agustinso** [comment]
Completely agree
