### ISSUE TITLE
Effective causing a game crash!

### ISSUE THREAD

**Issue by JustAHuman-xD** [Ladysnake/Effective#40]
Something is happening with effective that is causing a game crash:
![image](https://user-images.githubusercontent.com/65748158/147526580-2f9c9ec8-c7a2-439b-b4aa-6b33f558e20c.png)

Crash Report:
https://paste.gg/p/anonymous/58521a75616841c398a638887744ee2c

If you need a mod list I can post it

**Comment by AViewFromTheTop** [comment]
same

**Comment by srnyx** [comment]
Here's a crashy of it: https://crashy.net/lLUmRgjwavGOrOkpKVOT

**Comment by TheDerpu0ne** [comment]
yup, same here

**Comment by TheDerpu0ne** [comment]
even with just vanilla so it is effective doing it, I think the HashMap error is the problem, I have no idea how to fix it myself so we will just have to wait for now I suppose.

**Comment by rbroderi** [comment]
im getting the same issue.

**Comment by rbroderi** [comment]
looks like it is cause by public static final Set<WaterfallCloudGenerator> generators in src\main\java\ladysnake\effective\client\world\WaterfallCloudGenerators.java hashset modified in non thread safe manner.

**Comment by rbroderi** [comment]
just tested out using CopyOnWriteArraySet instead of the Hashset and that seems to resolve this issue as the CopyOnWriteArraySet is thread safe.
