### ISSUE TITLE
Lagging in the Nether

### ISSUE THREAD

**Issue by MDouglas345** [Ladysnake/Effective#42]
I have been experiencing insane lag in the nether and looked through my mods individually to find the culprit, and unfortunately, this lovely mod is it. I believe since the Nether is mostly liquid and since there are quite a number of entities that are in that lava there are constant splashes which causes this lag. Im no minecraft mod creator but I would think that if you could use instancing for the mesh or have a LOD where if an entity is too far then dont make it splash might help.

Again, Im no minecraft mod developer but can see where there can be some optimization routes to take.

**Comment by Xastabus** [comment]
What version of the mod are you running?  Effective 1.1 included many optimizations, performance fixes, and compatibility fixes that may address the problems you're experiencing.

I've been running Sollace's unofficial 1.1.0 version with some of the fixes that were proposed at the time and that greatly improved performance, especially in the nether.

Make sure you're on the latest release, and when reporting issues it is helpful to mention what version of the mod you are currently using.

**Comment by MDouglas345** [comment]
I am using Effective 1.1 on Fabric Minecraft 1.18; Is Sollace an addon for Effective?

**Comment by Xastabus** [comment]
No, Sollace is one of the contributors.  If you're running Effective 1.1 then you should have the improvements that were demonstrated in Sollace's unofficial build before those changes were merged into the main branch.

I just upgraded to 1.1 and ran a test in the nether. Nearby magma cubes swimming in lava can still drag down FPS but 1.1 still offers a huge performance improvement over 1.0.

Something that might help (aside from further optimizations to Effective) is adding the Entity Culling mod to your client if you don't already have it.  This will prevent magma cubes you can't actually see from being rendered, which should help your FPS.  I don't know whether or not it would also cull Effective's effects when you can't actually see them.
