### ISSUE TITLE
ConcurrentModificationException looking like its coming from Effective

### ISSUE THREAD

**Issue by WardenDrew** [Ladysnake/Effective#46]
Running Medieval Minecraft 1.18.1 v7 with effective added in on a server.
Only one of our players has this issue, everyone else is fine. If it matters, he chose Siren for his Origin's choice and spends most of his time underwater.

It doesn't seem to be repeatable in any specific area, and happens randomly, sometimes right after logging in, sometimes after several hours.

Crash Log Attached
[crash_log.txt](https://github.com/Ladysnake/Effective/files/7826782/crash_log.txt)

**Comment by r333mo** [comment]
#40
