### ISSUE TITLE
Cascade effects don't work with Sodium and Iris

### ISSUE THREAD

**Issue by SledgeDragon** [Ladysnake/Effective#5]
The cascade effects just don't appear and there is no sound either. Not sure if this issue is exclusive to compatibility with Sodium but I'm too lazy to find out lol. 

Also, sometimes splashes don't calculate properly if ticks are running behind or you're on a server.

**Comment by AViewFromTheTop** [comment]
Can confirm

**Comment by AViewFromTheTop** [comment]
Only Sodium causes this issue, I removed Iris from my mods folder and tested it again, nothing changed. Once I removed Sodium, the problem was gone.

**Comment by Arathain** [comment]
Have you tried summoning the particle in through command blocks? Obviously not a solution, but if it works via commands it's the issue that I suspect it to be

**Comment by AViewFromTheTop** [comment]
The mod doesn't add any new particle effects, it uses existing ones. I really don't know anything about Minecraft's rendering whatsoever, but looking at the source for the mod you can see something called particle.fsh in the shaders folder- I'd assume this causes the problem.

**Comment by DarianLStephens** [comment]
I don't know about the others, but I can summon the 'waterfall cloud' particle and see it no problem.

**Comment by DavidPipo** [comment]
I'm using sodium and I can't see the waterfall either

**Comment by supsm** [comment]
This also happens with canvas, and I have a screenshot 
![](https://media.discordapp.net/attachments/788895865897091082/920827083385606174/unknown.png)
It isn’t the shaders btw, it also happens with canvas standard and basic

**Comment by chris819t** [comment]
Yea im having the same issue as well with no cascades with sodium+iris

**Comment by DarianLStephens** [comment]
I don't know about anyone else, but I'm still not seeing cascades with Sodium, even if I remove Iris.
