### ISSUE TITLE
Black Splashes

### ISSUE THREAD

**Issue by rayman0** [Ladysnake/Effective#50]
I download the fabric 1.1v effective and the Textures are now black pls help
btw I remove sodium and some mods are forge

here are the mods
Edit I deleted mod that why you don't see it

![Capture](https://user-images.githubusercontent.com/97859414/149685759-decbbb82-c769-4b4b-9a69-4f54f5525441.PNG)

**Comment by Arathain** [comment]
This repository is for the Fabric version of the mod, for the Fabric modloader. That being said, removing optifine should fix it.

**Comment by rayman0** [comment]
> This repository is for the Fabric version of the mod, for the Fabric modloader. That being said, removing optifine should fix it.

ok I well try it

**Comment by rayman0** [comment]
> This repository is for the Fabric version of the mod, for the Fabric modloader. That being said, removing optifine should fix it.

well it does not work(forge one works)

**Comment by Dr-WeiAL** [comment]
I also got the black splash when I installed the sodium but it was gone after removing the sodium

**Comment by Dr-WeiAL** [comment]
Well, I found that after turning on the shader, the splash becomes normal. Even if the shader is turned off again, the splash will not turn back to black unless the game is restarted. 
![image](https://user-images.githubusercontent.com/47446553/149821831-ebfdbd6e-305c-4a35-9e17-b7e1829b292b.png)
![image](https://user-images.githubusercontent.com/47446553/149821874-9cc61e7b-71bb-4280-9e05-49b43c2eda7d.png)

**Comment by Redd56** [comment]
weird
