### ISSUE TITLE
how do i change the volume of a cascade?

### ISSUE THREAD

**Issue by username89213712** [Ladysnake/Effective#53]
when i go to the config file there is no place to edit the volume of the cascades, I use fabric

**Comment by DonomiteG** [comment]
While I don't think there is a way to turn down the volume of a cascade, if it's really annoying, you can disable it.

**I opened the .jar file using 7-Zip/WinRAR**

![image](https://user-images.githubusercontent.com/98487964/151263386-ae7ba8e3-f61c-4f63-9973-bdec3bcf6781.png)

**Then, I just deleted it.**

I don't know that much about code, so there's probably some way to make it quieter, but this should help.

**Comment by username89213712** [comment]
> 

how do i open the .jar as a folder?
