### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by QueenUlyana** [Ladysnake/Effective#54]
Terrible noise and a visual effect that can only be seen underwater. 
![2022-01-23_14 38 50](https://user-images.githubusercontent.com/83131824/150678436-4dac7a14-aead-44ae-9c96-4bd95c579e96.png)
![2022-01-23_14 38 52](https://user-images.githubusercontent.com/83131824/150678443-ce7ccddf-95bb-4ae2-b6ab-c1db4463f24f.png)

**Comment by DonomiteG** [comment]
Can confirm, occasionally happens when sand/gravel falls, in which case the water tries to fill up, accidentally causing this glitch.
