### ISSUE TITLE
Magma Cubes Cause Lag On Lava

### ISSUE THREAD

**Issue by DonomiteG** [Ladysnake/Effective#56]
Magma cubes bounce on the "sea level" lava in the Nether, causing continuous lag.
It spiked my game from 282 fps, to 131, then 30.

https://user-images.githubusercontent.com/98487964/151233305-c25724ec-cd90-4297-be44-693d1e04ec7e.mp4

**(Slight cut to fit 10MB, even without the cut, you can see my frames drop at the very start)**

List of my mods:
![image](https://user-images.githubusercontent.com/98487964/151232460-5df1b7a9-6e3c-4915-b71a-9a91ffa26cda.png)

**Comment by DonomiteG** [comment]
If any extra info is needed (RAM, specs) let me know

**Comment by Timolino456** [comment]
This is simply the Magma Cubes creating dozens to hundreds of lava particles flying around, causing a lot lag. It is the same for everyone.

**Comment by DonomiteG** [comment]
> It is the same for everyone.

Exactly, my post was intended for this to be possibly resolved or adjusted.

**Comment by BlueTheSniper** [comment]
I started a 1.18.1 survival world today and the second I entered the Nether after installing this mod my FPS dropped from around 60 to 1-3.
