### ISSUE TITLE
Forming Water source blocks underwater, causes Waterfall effect (That is also too loud)

### ISSUE THREAD

**Issue by Chris6ix** [Ladysnake/Effective#62]
Using for example Kelp underwater to from source blocks, the Waterfall effect appears, although there is no waterfall...

Also, the Waterfall sound is way too loud...pls turn it down or give us an option to reduce the volume for example in the `effective.properties` file

Otherwise, awesome mod!

**Comment by DanielDG10** [comment]
I also think the sound is too loud
