### ISSUE TITLE
splash rendering error

### ISSUE THREAD

**Issue by Dr-WeiAL** [Ladysnake/Effective#63]
![image](https://user-images.githubusercontent.com/47446553/153740431-7235d644-ed14-4cf2-9073-a5b42a511859.png)
![image](https://user-images.githubusercontent.com/47446553/153740439-23d81b61-6c19-4747-9148-9f2b08deaf8a.png)
Splashes are normal after turning on the light and shadow shader
![image](https://user-images.githubusercontent.com/47446553/153740679-c033b19b-9b12-4f75-a22b-eb7c50f1b028.png)
but splash works fine without iris installed

**Comment by doinkythederp** [comment]
I have this same issue, but I dont have Iris installed.
