### ISSUE TITLE
Black splashes (no other mods installed, just effective 1.1 and the fabric api)

### ISSUE THREAD

**Issue by NyannRR** [Ladysnake/Effective#67]
![image](https://user-images.githubusercontent.com/70542437/154874436-cb7d17d5-ccbb-4c64-8a71-53462bee944d.png)
It starts working again when I install Iris and enable any shaders
![image](https://user-images.githubusercontent.com/70542437/154874504-c2090ac9-518b-4f9c-9202-cd872d8d924e.png)

**Comment by redpanda453** [comment]
oof i hav that to how do i fix it?

**Comment by NyannRR** [comment]
> oof i hav that to how do i fix it?

Well, if I knew I wouldn't have posted it here, I think all we can do is just wait until a fix is released

**Comment by MIOGMIOG** [comment]
> ![image](https://user-images.githubusercontent.com/70542437/154874436-cb7d17d5-ccbb-4c64-8a71-53462bee944d.png) It starts working again when I install Iris and enable any shaders ![image](https://user-images.githubusercontent.com/70542437/154874504-c2090ac9-518b-4f9c-9202-cd872d8d924e.png)

this also happening for me
