### ISSUE TITLE
Waterfall sound fx way too loud

### ISSUE THREAD

**Issue by Xpert0** [Ladysnake/Effective#69]
They're blown out of proportion compared to all the other sounds of the game, maybe add a setting for the mod's sound volume?

**Comment by drathmorgh** [comment]
I have had the same issue so I deleted the sounds.mcmeta and no sounds now but its fine

**Comment by Xpert0** [comment]
Thank you! I'll do the same as the sound is very annoying, the rest if the mod is good

**Comment by gameo7** [comment]
i'm gonna see if i can edit the sound so it can be a lot quieter, if not then I'll just delete the sounds.mcmeta for now. hope this gets fixed soon!!
