### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Fleyzi** [Ladysnake/Effective#72]
So, if you launching the game, it's crashing at startup

Crash report: https://pastebin.com/erJ3kbzM

Log file: https://pastebin.com/YA6NTgxb

**I'm running on Minecraft 1.18.2**

**Comment by craftish37** [comment]
Mod can't be loaded on 1.18.2, please wait for the update :P

**Comment by GonzoStudioz** [comment]
Hopefully that update comes soon with optifabirc

**Comment by MoriyaShiine** [comment]
updated to 1.18.2
