### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Heamaci** [Ladysnake/Effective#74]
Not sure what could be causing it, but here is my crash log
[latest.log](https://github.com/Ladysnake/Effective/files/8366626/latest.log)

**Comment by Niketats** [comment]
you are using 1.18.2, when mod is for 1.18.1

**Comment by Pushkka** [comment]
When 1.18.2 version? Changelog says "update to 1.18.2"
-__-

**Comment by Niketats** [comment]
I'm not a developer. Snd where you saw about 1.18.2? Nothing about 1.18.2 in changelog and game version pointed as 1.18.1
![Screenshot_2022-03-29-03-16-17-464_com android chrome](https://user-images.githubusercontent.com/68917520/160508095-35d847b4-74d2-4c91-a08e-17659dc3edaa.jpg)

**Comment by Heamaci** [comment]
> I'm not a developer. Snd where you saw about 1.18.2? Nothing about 1.18.2 in changelog and game version pointed as 1.18.1 ![Screenshot_2022-03-29-03-16-17-464_com android chrome](https://user-images.githubusercontent.com/68917520/160508095-35d847b4-74d2-4c91-a08e-17659dc3edaa.jpg)

My mistake, I assumed it was 18.2 because it had updated recently

**Comment by Niketats** [comment]
Hm, they are pushed a commit with 1.18.2 support, so i think they will publish 1.18.2 in a few days
