### ISSUE TITLE
Are you going to update to 1.18.2?

### ISSUE THREAD

**Issue by TheButterbrotMan** [Ladysnake/Effective#75]
Hey, i just wanna know if you will update to 1.18.2?

Also theres a lot of pulls. Maybe you can use some of them.

https://github.com/Ladysnake/Effective/pulls

**Comment by C5D3C5F4** [comment]
当然，我们想看到这些有趣的东西。
Of course, we want to see these interesting things.

**Comment by MoriyaShiine** [comment]
There's a 1.18.2 branch already, release should be soon-ish
