### ISSUE TITLE
Game Crash On Startup

### ISSUE THREAD

**Issue by Wyrdhare** [Ladysnake/Effective#76]
Game crashes and gives Error Code 1 when I start Minecraft with Fabric while Effective mod is in the Mods folder.

Don't really need a picture, because it is inevitable, if this is specifically the cause.

Log File:
[latest.log](https://github.com/Ladysnake/Effective/files/8389958/latest.log)

Tried running with just Effective mod and requisite Fabric API and got this:
[crash-2022-03-31_23.49.23-client.txt](https://github.com/Ladysnake/Effective/files/8389998/crash-2022-03-31_23.49.23-client.txt)
[latest.log](https://github.com/Ladysnake/Effective/files/8390013/latest.log)

**Comment by MoriyaShiine** [comment]
Effective isn't on 1.18.2 yet; update is probably today
