### ISSUE TITLE
Incompatible mod set

### ISSUE THREAD

**Issue by ebaystudio** [Ladysnake/Effective#84]
Just got this error when running it with the newest "Better Minecraft" modpack that updated to the newest fabric loader. 

> Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Effective' (effective) 1.2 with any version that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'Effective' (effective) 1.2 requires any version between 1.18- (inclusive) and 1.18.2 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Xiribidus** [comment]
Try using the latest version of effective, 1.2 does not work on Minecraft 1.18.2

**Comment by ebaystudio** [comment]
Don't know how I got the older file. but that was it. Thanks for the quick reply
