### ISSUE TITLE
Waterfall Cloud Generator Crash: Crashes Server

### ISSUE THREAD

**Issue by BrotherLeon** [Ladysnake/Effective#86]
I'm not super sure what is going on other than the stacktrace almost immediately pointing here. I was playing on the Deathdusk Discord roleplay server and it crashed the server itself.

This is a server-side crash report that I obtained from the mod who was looking into this issue with me.
https://bytebin.lucko.me/Us7xVNKaww

**Comment by BrotherLeon** [comment]
Also seems similar to #40, but I don't know enough to say for sure.

**Comment by TheButterbrotMan** [comment]
https://github.com/Ladysnake/Effective/pull/83
