### ISSUE TITLE
Water splashes get really weird with the fluid physics mod installed

### ISSUE THREAD

**Issue by Sunconure11** [Ladysnake/Effective#88]
![image](https://user-images.githubusercontent.com/5614902/168626556-f33e0be9-a631-4a6e-ba79-d29f4870198f.png)

https://www.curseforge.com/minecraft/mc-mods/fluid-physics

**Comment by Sunconure11** [comment]
The resultant interactions between the two mods creates some immense lag, due to all of the particle effects.

**Comment by Sunconure11** [comment]
@doctor4t Sorry about the ping. I just feel it’s urgent for you to look into this, since the lag it causes is nasty

**Comment by doctor4t** [comment]
Disable flowing water spawning particles on first update tick in the config
