### ISSUE TITLE
Splashes texture is black

### ISSUE THREAD

**Issue by th3heindnsiw** [Ladysnake/Effective#90]
Whenever an entity falls into water, the splashes are black for some reason.

**Comment by ZenoCoding** [comment]
can confirm, not sure why this is :/

**Comment by fu-raz** [comment]
For me they are only black when using a shader like Continuum. On BSL they look fine

**Comment by lonefelidae16** [comment]
Please take your screenshot, or is this issue related to #96 ?

**Comment by Brittank88** [comment]
> is this issue related to #96 ?

Now my only question is why what looks like a perfectly good PR hasn't been merged yet, but maybe there's reasons I'm unaware of.
