### ISSUE TITLE
[Suggestion] Water Waves effect from running boat

### ISSUE THREAD

**Issue by NaiNonTH** [Ladysnake/Effective#91]
It would be cool and more realistic if there was a waves effect appearing beneath a boat.

![2022-06-01_19 23 59](https://user-images.githubusercontent.com/61338902/171404422-da33d8d1-e0d3-48e5-8399-ec0ebc4bf16c.png)

**Comment by dophire** [comment]
Wakes mod does this

**Comment by doctor4t** [comment]
I'd say use the wakes mod. While I would love to have some included in Effective, everything I tried was a bit underwhelming and didn't work how I wanted it to. The Wakes mod's wakes are absolutely gorgeous though!
