### ISSUE TITLE
Crashing for 1.18.2 realms 

### ISSUE THREAD

**Issue by NicKnack819** [Ladysnake/Effective#93]
The game crashed on the realm due to this mod while I was playing on a realm that hasn't been updated to 1.19 yet and it may take a bit for the owner to update so if there is a temporary quick fix please let me know.

The Created Logs From The NotEnoughCrashes Mod:
https://bytebin.lucko.me/xMp373z2Ny
https://crashy.net/ctC0LUYwwN2MkzJMQkxv

**Comment by NicKnack819** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/60555295/172526010-5944fa6a-ee3c-4fc8-bdde-4e6ba15f567f.png)

**Comment by lonefelidae16** [comment]
same as #80, #85

see #87

**Comment by NicKnack819** [comment]
> same as #80, #85
> 
> see #87

So should I close this issue?

**Comment by lonefelidae16** [comment]
> So should I close this issue?

I would prefer not to close this issue in the sense of communicating problem to the owner; these crashes are not solved yet.

**Comment by EGOIST1372** [comment]
@doctor4t @Pyrofab Hey guys, there are 5 pull request is waiting to be merged and an update to this many crashes and black splashes issues would be nice and appreciated.
thanks <3

**Comment by SekoiaTree** [comment]
One of those is a draft, and another has since been closed (it was mine) so there's only 3. For the rest yeah.
