### ISSUE TITLE
throwing lingering potions into bodies of water creates huge splashes that can crash your game if not stopped

### ISSUE THREAD

**Issue by Notkrono** [Ladysnake/Effective#97]
the lingering potion can cause a crash if enough of them are thrown into a body of water.

https://youtu.be/c6AczkLwZ1o

**Comment by lonefelidae16** [comment]
The crash you mentioned was caught.
[crash-2022-06-21_11.39.53-client.txt](https://github.com/Ladysnake/Effective/files/8945336/crash-2022-06-21_11.39.53-client.txt)
 
To reproduce: throw huge number of lingering potions into the water.

Thank you for your report, I’m waiting for the PR to be merged.
