### ISSUE TITLE
Lava splashes don't work 

### ISSUE THREAD

**Issue by TailOrTaily** [Ladysnake/Effective#98]
i don't know if it's only me but on 1.19 and with effective 1.2.2 the lava splashes don't work with anything

**Comment by TailOrTaily** [comment]
![1](https://user-images.githubusercontent.com/104798528/174685171-9baa5f9d-31ef-4161-930b-d07bd59167e8.png)
![2](https://user-images.githubusercontent.com/104798528/174685172-a7c735ac-6097-4e0a-adbe-84609baa3dfc.png)
i forgot to say this and ask is it because of my other mods these are the ones im using combined with Effective

**Comment by Xiribidus** [comment]
Lava splashes have been removed in the last few versions since they didn't end up working as well and being more buggy than useful. (And no they will not be re-added, in case you are asking yourself, sorry)
