### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by srnyx** [Ladysnake/Effective#99]
Upload the mod to [Modrinth](https://modrinth.com)

**Comment by srnyx** [comment]
@doctor4t please 🙏

**Comment by doctor4t** [comment]
I'll upload to modrinth once they have their planned reward program implemented

**Comment by Insprill** [comment]
@doctor4t Modrinth just released their monetization program. You can read more about it [here](https://blog.modrinth.com/creator-monetization-beta).
